/* eslint-disable max-len */
const tagKeywords = {
  "React": [
    "react", "jsx", "tsx", "component", "hook", "usestate", "useeffect", "usecontext",
    "usereducer", "usememo", "usecallback", "useref", "custom hook", "props", "state",
    "virtual dom", "react native", "nextjs", "next.js", "gatsby", "create react app",
    "react router", "react query", "redux", "mobx", "context api", "react lifecycle",
    "render", "mount", "unmount", "reconciliation",
    "fragment", "memo", "pure component", "higher order component", "hoc",
    "render props", "compound component", "controlled component", "uncontrolled component",
  ],
  "JavaScript": [
    "javascript", "js", "ecmascript", "es6", "es2015", "es2020", "es2021", "function",
    "variable", "const", "let", "var", "object", "array", "promise", "async", "await",
    "callback", "closure", "scope", "hoisting", "prototype", "this", "bind", "call",
    "apply", "arrow function", "destructuring", "spread operator", "rest parameter",
    "template literal", "set", "weakmap", "weakset", "proxy",
    "reflect", "generator", "iterator", "module", "import", "export", "class",
    "inheritance", "polymorphism", "encapsulation", "event loop", "microtask",
    "macrotask", "node", "nodejs", "npm", "yarn", "package.json", "webpack",
    "babel", "typescript", "flow", "eslint", "prettier", "jest", "mocha",
  ],
  "Frontend": [
    "frontend", "front-end", "ui", "ux", "user interface", "user experience",
    "css", "html", "html5", "css3", "dom", "browser", "responsive", "mobile first",
    "web design", "layout", "grid", "flexbox", "media queries", "viewport",
    "accessibility", "aria", "semantic html", "progressive enhancement",
    "graceful degradation", "cross browser", "polyfill", "shim", "vendor prefix",
    "critical css", "above the fold", "lazy loading", "code splitting",
    "tree shaking", "bundling", "minification", "compression", "caching",
    "service worker", "pwa", "progressive web app", "spa", "single page application",
    "mpa", "multi page application", "ssr", "server side rendering", "csr",
    "client side rendering",
  ],
  "Backend": [
    "backend", "back-end", "server", "api", "rest", "restful", "graphql",
    "database", "mongodb", "mysql", "postgresql", "sqlite", "redis", "memcached",
    "express", "fastify", "koa", "hapi", "nestjs", "authentication", "authorization",
    "jwt", "oauth", "oauth2", "session", "cookie", "cors", "csrf", "xss",
    "sql injection", "middleware", "routing", "controller", "model", "view",
    "mvc", "mvp", "mvvm", "repository pattern", "service layer", "dto",
    "orm", "odm", "mongoose", "sequelize", "prisma", "typeorm", "knex",
    "migration", "seed", "transaction", "acid", "nosql", "document store",
    "key value", "column family", "graph database", "time series", "search engine",
    "elasticsearch", "solr", "lucene", "indexing", "sharding", "replication",
    "load balancing", "reverse proxy", "nginx", "apache", "caching", "cdn",
  ],
  "Tutorial": [
    "tutorial", "guide", "how to", "step by step", "learn", "beginner",
    "intermediate", "advanced", "course", "getting started", "introduction",
    "basics", "fundamentals", "walkthrough", "hands on", "practical",
    "example", "demo", "workshop", "bootcamp", "crash course", "deep dive",
    "masterclass", "certification", "training", "skill building", "practice",
    "exercise", "assignment", "project", "case study", "best practices",
    "tips", "tricks", "common mistakes", "debugging",
    "code review", "refactoring", "optimization", "performance tuning",
  ],
  "Web Development": [
    "web development", "web dev", "fullstack", "full-stack", "full stack",
    "developer", "development", "website", "web app", "web application",
    "web service", "web api", "web framework", "web server", "web client",
    "web browser", "web standards", "w3c", "http", "https", "tcp", "ip",
    "dns", "domain", "subdomain", "url", "uri", "routing", "navigation",
    "seo", "search engine optimization", "meta tags", "sitemap", "robots.txt",
    "analytics", "monitoring", "logging", "error handling",
    "exception handling", "validation", "encryption",
    "decryption", "hashing", "bcrypt", "ssl", "tls", "certificate",
  ],
  "CSS": [
    "css", "css3", "stylesheet", "cascading style sheets", "selector",
    "property", "value", "declaration", "specificity", "inheritance",
    "box model", "margin", "padding", "border", "content", "display",
    "position", "float", "clear", "flexbox", "grid", "css grid", "flex",
    "responsive design", "media queries", "breakpoint", "mobile first",
    "desktop first", "bootstrap", "tailwind", "bulma", "foundation",
    "material ui", "ant design", "chakra ui", "styled components",
    "emotion", "css modules", "css in js", "sass", "scss", "less",
    "stylus", "postcss", "autoprefixer", "animation", "transition",
    "transform", "keyframes", "hover", "focus", "active", "pseudo class",
    "pseudo element", "before", "after", "nth child", "first child",
    "last child", "only child", "root", "custom properties", "css variables",
    "calc", "clamp", "min", "max", "viewport units", "rem", "em", "px",
  ],
  "Database": [
    "database", "db", "dbms", "rdbms", "sql", "nosql", "relational",
    "non relational", "table", "row", "column", "field", "record",
    "primary key", "foreign key", "index", "constraint", "normalization",
    "denormalization", "join", "inner join", "left join", "right join",
    "full join", "cross join", "union", "intersection", "aggregation",
    "group by", "having", "order by", "limit", "offset", "pagination",
    "mongodb", "mysql", "postgresql", "sqlite", "oracle", "sql server",
    "redis", "cassandra", "dynamodb", "couchdb", "firebase", "firestore",
    "supabase", "planetscale", "cockroachdb", "query", "schema", "migration",
    "backup", "restore", "replication", "sharding", "partitioning",
    "transaction", "acid", "consistency", "isolation", "durability",
    "atomicity", "deadlock", "race condition", "connection pooling",
  ],
  "Mobile": [
    "mobile", "mobile development", "mobile app", "android", "ios",
    "react native", "flutter", "ionic", "cordova", "phonegap", "xamarin",
    "native", "hybrid", "cross platform", "responsive", "adaptive",
    "mobile first", "touch", "gesture", "swipe", "tap", "pinch", "zoom",
    "accelerometer", "gyroscope", "gps", "camera", "microphone", "bluetooth",
    "nfc", "push notification", "local notification", "background processing",
    "offline", "sync", "storage", "cache", "performance", "battery",
    "memory", "cpu", "gpu", "app store", "play store", "deployment",
    "testing", "emulator", "simulator", "device", "debugging", "profiling",
    "android studio", "xcode", "gradle", "cocoapods",
    "swift", "kotlin", "objective c", "java", "dart", "javascript",
  ],
  "DevOps": [
    "devops", "deployment", "ci/cd", "continuous integration", "continuous deployment",
    "continuous delivery", "pipeline", "build", "test", "release", "docker",
    "container", "containerization", "kubernetes", "k8s", "orchestration",
    "microservices", "service mesh", "istio", "helm", "terraform", "ansible",
    "puppet", "chef", "infrastructure as code", "iac", "provisioning",
    "configuration management", "monitoring", "logging", "alerting", "metrics",
    "observability", "tracing", "apm", "github actions", "gitlab ci", "jenkins",
    "travis ci", "circle ci", "azure devops", "aws codepipeline", "aws",
    "amazon web services", "azure", "gcp", "google cloud platform",
    "cloud", "cloud computing", "serverless", "lambda", "functions",
    "edge computing", "cdn", "load balancer", "auto scaling", "health check",
    "blue green deployment", "canary deployment", "rolling deployment",
  ],
  "Security": [
    "security", "cybersecurity", "information security", "application security",
    "network security", "data security", "authentication", "authorization",
    "access control", "rbac", "abac", "jwt", "oauth", "oauth2", "saml",
    "openid connect", "sso", "single sign on", "mfa", "multi factor authentication",
    "2fa", "two factor authentication", "password", "hash", "salt", "bcrypt",
    "scrypt", "argon2", "encryption", "decryption", "symmetric", "asymmetric",
    "public key", "private key", "certificate", "pki", "ssl", "tls", "https",
    "vulnerability", "exploit", "penetration testing", "ethical hacking",
    "security audit", "code review", "static analysis", "dynamic analysis",
    "owasp", "sql injection", "xss", "csrf", "clickjacking",
    "session hijacking", "man in the middle", "dos", "ddos", "firewall",
    "intrusion detection", "intrusion prevention", "antivirus", "malware",
    "ransomware", "phishing", "social engineering", "zero day", "patch",
  ],
  "Performance": [
    "performance", "optimization", "speed", "loading", "fast", "slow",
    "bottleneck", "profiling", "benchmarking", "monitoring", "metrics",
    "web vitals", "core web vitals", "lcp", "fid", "cls",
    "ttfb", "fcp", "tti", "caching", "cache", "browser cache", "http cache",
    "etag", "last modified", "cache control", "expires", "lazy loading",
    "eager loading", "preloading", "prefetching", "code splitting",
    "bundle splitting", "tree shaking", "dead code elimination",
    "minification", "uglification", "compression", "gzip", "brotli",
    "image optimization", "webp", "avif", "svg", "sprite", "icon font",
    "cdn", "content delivery network", "edge caching", "database optimization",
    "query optimization", "indexing", "connection pooling", "load balancing",
    "horizontal scaling", "vertical scaling", "auto scaling", "throttling",
    "rate limiting", "debouncing", "memoization", "pagination", "virtual scrolling",
  ],
  "Testing": [
    "testing", "test", "qa", "quality assurance", "unit test", "integration test",
    "end to end test", "e2e", "functional test", "acceptance test", "smoke test",
    "regression test", "performance test", "load test", "stress test",
    "security test", "usability test", "accessibility test", "manual test",
    "automated test", "test automation", "test driven development", "tdd",
    "bdd", "test case", "test suite",
    "test runner", "test framework", "assertion", "mock", "stub", "spy",
    "fixture", "setup", "teardown", "jest", "mocha", "jasmine", "vitest",
    "cypress", "selenium", "puppeteer", "playwright", "webdriver",
    "testing library", "react testing library",
    "protractor", "nightwatch", "cucumber", "gherkin", "spec", "describe",
    "code coverage", "mutation testing", "snapshot testing", "visual testing", "cross browser testing",
  ],
  "API": [
    "api", "application programming interface", "rest", "restful", "rest api",
    "graphql", "grpc", "soap", "rpc", "json rpc", "xml rpc", "endpoint",
    "route", "resource", "http", "https", "method", "get", "post", "put",
    "patch", "delete", "head", "options", "status code", "200", "201",
    "204", "400", "401", "403", "404", "500", "request", "response",
    "header", "body", "payload", "parameter", "query parameter", "path parameter",
    "json", "xml", "yaml", "csv", "form data", "multipart", "content type",
    "accept", "authorization", "bearer token", "api key", "rate limiting",
    "throttling", "pagination", "sorting", "filtering", "search", "versioning",
    "documentation", "swagger", "openapi", "postman", "insomnia", "curl",
    "webhook", "callback", "event driven", "real time", "websocket",
    "server sent events", "sse", "polling", "long polling", "microservices",
    "service mesh", "api gateway", "reverse proxy", "load balancer",
  ],
  "Framework": [
    "framework", "library", "toolkit", "boilerplate", "template", "scaffold",
    "express", "expressjs", "fastify", "koa", "hapi", "nestjs", "sails",
    "meteor", "feathers", "loopback", "angular", "angularjs", "vue",
    "vuejs", "nuxt", "nuxtjs", "svelte", "sveltekit", "react", "nextjs",
    "gatsby", "remix", "solid", "solidjs", "lit", "stencil", "alpine",
    "stimulus", "htmx", "jquery", "knockout",
    "django", "flask", "fastapi", "tornado", "bottle", "pyramid",
    "rails", "ruby on rails", "sinatra", "spring", "spring boot",
    "laravel", "symfony", "codeigniter", "yii", "zend", "cakephp",
    "asp.net", "dotnet", "blazor", "gin", "echo", "fiber", "beego",
    "revel", "phoenix", "plug", "actix", "rocket", "axum",
    "warp", "hyper", "tokio", "async",
  ],
  "Programming Languages": [
    "programming language", "language", "syntax", "semantics", "compiler",
    "interpreter", "runtime", "virtual machine", "bytecode", "machine code",
    "assembly", "low level", "high level", "procedural", "object oriented",
    "functional", "declarative", "imperative", "scripting", "markup",
    "javascript", "typescript", "python", "java", "c", "c++", "c#",
    "go", "golang", "rust", "kotlin", "swift", "objective c", "ruby",
    "php", "perl", "scala", "clojure", "haskell", "erlang", "elixir",
    "dart", "lua", "r", "matlab", "fortran", "cobol", "pascal",
    "delphi", "visual basic", "f#", "ocaml", "lisp", "scheme", "prolog",
    "sql", "html", "css", "xml", "json", "yaml", "toml", "markdown",
    "latex", "bash", "powershell", "regex", "regular expression",
  ],
  "Cloud Computing": [
    "cloud", "cloud computing", "cloud services", "cloud provider", "saas",
    "software as a service", "paas", "platform as a service", "iaas",
    "infrastructure as a service", "faas", "function as a service",
    "serverless", "edge computing", "fog computing", "hybrid cloud",
    "multi cloud", "private cloud", "public cloud", "community cloud",
    "aws", "amazon web services", "ec2", "s3", "rds", "lambda", "cloudfront",
    "route 53", "vpc", "iam", "cloudformation", "cloudwatch", "sns", "sqs",
    "azure", "microsoft azure", "virtual machines", "blob storage", "sql database",
    "functions", "app service", "active directory", "resource manager",
    "monitor", "service bus", "event hub", "gcp", "google cloud platform",
    "compute engine", "cloud storage", "cloud sql", "cloud functions",
    "app engine", "kubernetes engine", "bigquery", "cloud pub sub",
    "cloud cdn", "cloud iam", "cloud deployment manager", "stackdriver",
    "scalability",
    "fault tolerance", "disaster recovery", "backup", "restore", "migration",
  ],
  "Artificial Intelligence": [
    "artificial intelligence", "ai", "machine learning", "ml", "deep learning",
    "neural network", "artificial neural network", "ann", "convolutional neural network",
    "cnn", "recurrent neural network", "rnn", "lstm", "gru", "transformer",
    "attention mechanism", "bert", "gpt", "nlp", "natural language processing",
    "natural language understanding", "nlu", "natural language generation",
    "nlg", "computer vision", "image recognition", "object detection",
    "semantic segmentation", "instance segmentation", "face recognition",
    "speech recognition", "text to speech", "speech to text", "chatbot",
    "virtual assistant", "recommendation system", "collaborative filtering",
    "content based filtering", "reinforcement learning", "supervised learning",
    "unsupervised learning", "semi supervised learning", "classification",
    "regression", "clustering", "dimensionality reduction", "feature engineering",
    "feature selection", "cross validation", "overfitting", "underfitting",
    "bias", "variance", "gradient descent", "backpropagation", "optimization",
    "hyperparameter tuning", "model selection", "ensemble methods",
    "random forest", "support vector machine", "svm", "decision tree",
    "naive bayes", "k means", "hierarchical clustering", "pca", "lda",
    "tensorflow", "pytorch", "keras", "scikit learn", "opencv", "nltk",
    "spacy", "hugging face", "transformers", "pandas", "numpy", "matplotlib",
    "jupyter", "colab", "gpu", "cuda", "tpu", "edge ai", "federated learning",
    "explainable ai", "xai", "ai ethics", "bias in ai", "fairness",
    "adversarial attack", "adversarial example", "generative ai", "gans",
    "variational autoencoder", "vae", "diffusion model", "stable diffusion",
  ],
  "Blockchain": [
    "blockchain", "distributed ledger", "cryptocurrency", "crypto", "bitcoin",
    "ethereum", "altcoin", "token", "coin", "digital currency", "virtual currency",
    "decentralized", "centralized", "peer to peer", "p2p", "consensus",
    "proof of work", "pow", "proof of stake", "pos", "mining", "miner",
    "node", "full node", "light node", "validator", "staking", "hash",
    "hash function", "merkle tree", "block", "transaction", "wallet",
    "private key", "public key", "address", "smart contract", "dapp",
    "decentralized application", "web3", "defi", "decentralized finance",
    "nft", "non fungible token", "dao",
    "oracles", "cross chain", "interoperability", "layer 1",
    "layer 2", "scaling", "sharding", "rollup", "optimistic rollup",
    "zk rollup", "zero knowledge", "zk snark", "zk stark", "privacy coin",
    "atomic swap", "fork", "hard fork", "soft fork", "governance",
    "tokenomics", "yield farming", "liquidity mining", "stablecoin",
    "cbdc", "central bank digital currency", "ico", "ido", "ipo",
    "exchange", "dex", "decentralized exchange", "cex", "centralized exchange",
    "trading", "hodl", "bull market", "bear market", "volatility",
  ],
  "Quantum Computing": [
    "quantum", "quantum computing", "quantum computer", "quantum processor",
    "quantum supremacy", "quantum advantage", "qubit", "quantum bit",
    "superposition", "entanglement", "quantum entanglement", "coherence",
    "decoherence", "quantum decoherence", "quantum gate", "quantum circuit",
    "quantum algorithm", "quantum programming", "quantum software",
    "quantum simulation", "quantum machine learning", "quantum ai",
    "quantum cryptography", "quantum key distribution", "quantum communication",
    "quantum internet", "quantum network", "quantum sensing", "quantum metrology",
    "quantum error correction", "quantum fault tolerance", "quantum noise",
    "quantum channel", "quantum state", "quantum measurement", "quantum teleportation",
    "quantum annealing", "adiabatic quantum computing", "gate model",
    "quantum assembly", "openqasm", "qiskit", "cirq", "pennylane",
    "quantum development kit", "q#", "quantum computing service",
    "ibm quantum", "google quantum", "microsoft quantum", "rigetti",
    "ionq", "quantum hardware", "superconducting qubit", "trapped ion",
    "photonic qubit", "topological qubit", "quantum volume", "quantum fidelity",
  ],
  "Augmented Reality Virtual Reality": [
    "augmented reality", "ar", "virtual reality", "vr", "mixed reality",
    "mr", "extended reality", "xr", "immersive technology", "spatial computing",
    "head mounted display", "hmd", "headset", "glasses", "smart glasses",
    "oculus", "meta quest", "hololens", "magic leap", "apple vision pro",
    "htc vive", "valve index", "pico", "varjo", "tracking", "motion tracking",
    "hand tracking", "eye tracking", "facial tracking", "body tracking",
    "inside out tracking", "outside in tracking", "6dof", "3dof",
    "degrees of freedom", "spatial mapping", "slam", "simultaneous localization and mapping",
    "world tracking", "plane detection", "marker based", "markerless",
    "computer vision", "depth sensing", "lidar", "tof", "time of flight",
    "stereoscopic", "360 degree", "panoramic", "photogrammetry", "volumetric",
    "hologram", "holographic", "avatar", "digital twin", "virtual world",
    "metaverse", "virtual environment", "simulation", "training", "education",
    "entertainment", "gaming", "social vr", "collaboration", "remote work",
    "telepresence", "haptic feedback", "force feedback", "tactile", "gesture",
    "voice control", "gaze control", "brain computer interface", "bci",
    "unity", "unreal engine", "arkit", "arcore", "webxr", "aframe",
    "three.js", "babylon.js", "8th wall", "spark ar", "lens studio",
  ],
  "Health and Fitness": [
    "health", "fitness", "wellness", "wellbeing", "exercise", "workout",
    "training", "physical activity", "cardio", "cardiovascular", "strength training",
    "resistance training", "weight lifting", "bodyweight", "calisthenics",
    "yoga", "pilates", "stretching", "flexibility", "mobility", "balance",
    "endurance", "stamina", "hiit", "high intensity interval training",
    "crossfit", "functional fitness", "sports", "athletics",
    "running", "jogging", "walking", "cycling", "swimming", "dancing",
    "martial arts", "boxing", "kickboxing", "gymnastics", "climbing",
    "hiking", "outdoor activities", "nutrition", "diet", "healthy eating",
    "balanced diet", "meal planning", "meal prep", "calorie counting",
    "macronutrients", "micronutrients", "protein", "carbohydrates", "fats",
    "vitamins", "minerals", "supplements", "hydration", "water intake",
    "sleep", "rest", "recovery", "stress management", "meditation",
    "mindfulness", "mental health", "anxiety", "depression", "therapy",
    "counseling", "self care", "body composition", "weight management",
    "fat loss", "muscle gain", "metabolism", "bmr", "basal metabolic rate",
    "heart rate", "blood pressure", "cholesterol", "diabetes", "prevention",
    "rehabilitation", "injury prevention", "first aid", "healthcare",
    "medical", "doctor", "physician", "nurse", "hospital", "clinic",
  ],
  "Food and Cooking": [
    "food", "cooking", "culinary", "cuisine", "recipe", "ingredient",
    "meal", "dish", "course", "appetizer", "starter", "main course",
    "entree", "dessert", "side dish", "snack", "breakfast", "lunch",
    "dinner", "supper", "brunch", "buffet", "feast", "banquet",
    "preparation", "prep", "cooking method", "baking", "roasting",
    "grilling", "frying", "sauteing", "boiling", "steaming", "poaching",
    "braising", "stewing", "slow cooking", "pressure cooking",
    "curing", "marinating", "seasoning", "spice", "herb", "salt",
    "pepper", "garlic", "onion", "ginger", "chili", "paprika",
    "oregano", "basil", "thyme", "rosemary", "parsley", "cilantro",
    "kitchen", "cookware", "utensil", "knife", "cutting board", "pan",
    "pot", "oven", "stove", "microwave", "blender", "food processor",
    "mixer", "whisk", "spatula", "tongs", "ladle", "measuring cup",
    "scale", "recipe book", "cookbook",
    "chef", "cook", "baker", "pastry chef", "restaurant", "cafe",
    "bakery", "deli", "food truck", "catering", "meal delivery",
    "grocery", "organic",
    "seasonal", "fresh", "frozen", "canned", "processed", "homemade",
    "comfort food", "fast food", "street food", "ethnic food",
    "international cuisine", "vegetarian", "vegan", "gluten free",
    "dairy free", "keto", "paleo", "mediterranean", "asian", "italian",
    "mexican", "indian", "chinese", "japanese", "thai", "french",
  ],
  "Education and Learning": [
    "education", "learning", "teaching", "instruction", "pedagogy",
    "curriculum", "syllabus", "course", "class", "lesson", "lecture",
    "seminar", "workshop", "tutorial", "study", "research", "homework",
    "assignment", "project", "exam", "test", "quiz", "assessment",
    "evaluation", "grading", "feedback", "school", "elementary",
    "primary", "secondary", "high school", "college", "university",
    "academy", "institute", "campus", "classroom", "laboratory",
    "library", "student", "pupil", "learner", "teacher", "educator",
    "instructor", "professor", "tutor", "mentor", "coach", "principal",
    "headmaster", "dean", "academic", "scholar", "researcher",
    "degree", "diploma", "certificate", "qualification", "credential",
    "major", "minor", "specialization", "concentration", "field of study",
    "discipline", "subject", "topic", "chapter", "module", "unit",
    "online learning", "e-learning", "distance learning", "remote learning",
    "blended learning", "hybrid learning", "mooc", "massive open online course",
    "lms", "learning management system", "educational technology",
    "edtech", "digital learning", "interactive learning", "gamification",
    "virtual classroom", "webinar", "video conference", "educational app",
    "learning platform", "skill development", "professional development",
    "continuing education", "lifelong learning", "adult education",
    "vocational training", "apprenticeship", "internship", "practicum",
    "study group", "peer learning", "collaborative learning", "study skills",
    "note taking", "time management", "exam preparation", "test taking",
    "memory techniques", "critical thinking", "problem solving",
    "creativity", "innovation", "knowledge", "wisdom", "intelligence",
  ],
  "Software Architecture": [
    "software architecture", "system architecture", "architecture pattern",
    "design pattern", "architectural style", "clean architecture",
    "hexagonal architecture", "onion architecture", "layered architecture",
    "microservices", "monolith", "modular monolith", "service oriented architecture",
    "soa", "event driven architecture", "cqrs", "command query responsibility segregation",
    "event sourcing", "domain driven design", "ddd", "bounded context",
    "aggregate", "entity", "value object", "repository", "singleton", "observer", "strategy", "command", "facade",
    "adapter", "decorator", "proxy", "mvc", "mvp", "mvvm", "component",
    "service", "controller", "model", "view", "separation of concerns",
    "single responsibility principle", "open closed principle",
    "liskov substitution principle", "interface segregation principle",
    "dependency inversion principle", "solid principles", "dry",
    "dont repeat yourself", "kiss", "keep it simple stupid", "yagni",
    "you arent gonna need it", "coupling", "cohesion", "abstraction",
    "encapsulation", "inheritance", "polymorphism", "composition",
    "aggregation", "dependency injection", "inversion of control",
    "aspect oriented programming", "aop", "cross cutting concerns",
    "scalability", "performance", "maintainability", "testability",
    "flexibility", "extensibility", "reusability", "modularity",
    "loose coupling", "high cohesion", "code quality", "technical debt",
    "refactoring", "code review", "architectural review", "documentation",
  ],
  "Environment and Sustainability": [
    "environment", "environmental", "sustainability", "sustainable",
    "green", "eco", "ecological", "climate", "climate change",
    "global warming", "carbon footprint", "carbon neutral", "carbon negative",
    "greenhouse gas", "emission", "pollution", "air pollution",
    "water pollution", "soil pollution", "noise pollution", "contamination",
    "waste", "waste management", "recycling", "upcycling", "reuse",
    "reduce", "circular economy", "zero waste", "biodegradable",
    "compostable", "renewable", "non renewable", "fossil fuel",
    "clean energy", "renewable energy", "solar power", "wind power",
    "hydroelectric", "geothermal", "biomass", "nuclear energy",
    "energy efficiency", "conservation", "biodiversity", "ecosystem",
    "habitat", "wildlife", "endangered species", "deforestation",
    "reforestation", "afforestation", "sustainable agriculture",
    "organic farming", "permaculture", "water conservation",
    "drought", "flood", "natural disaster", "environmental impact",
    "life cycle assessment", "lca", "environmental footprint",
    "green technology", "clean technology", "eco friendly",
    "sustainable development", "green building", "leed certification",
    "energy star", "carbon offset", "carbon credit",
    "environmental policy", "epa", "environmental protection agency",
    "paris agreement", "kyoto protocol", "ipcc", "intergovernmental panel on climate change",
  ],
  "Fruits": [
    "fruits", "fresh fruit", "tropical fruit", "citrus fruit", "berry",
    "stone fruit", "apple", "red apple", "green apple", "granny smith",
    "gala", "fuji", "honeycrisp", "banana", "plantain", "orange",
    "blood orange", "navel orange", "mandarin", "tangerine", "clementine",
    "grapes", "red grapes", "green grapes", "seedless grapes", "raisins",
    "mango", "alphonso mango", "kent mango", "pineapple", "strawberry",
    "blueberry", "raspberry", "blackberry", "cranberry", "gooseberry",
    "kiwi", "kiwifruit", "papaya", "papaw", "watermelon", "cantaloupe",
    "honeydew melon", "pomegranate", "peach", "nectarine", "plum",
    "apricot", "cherry", "sweet cherry", "sour cherry", "guava",
    "lemon", "lime", "grapefruit", "avocado", "coconut", "date",
    "fig", "passion fruit", "dragon fruit", "star fruit", "carambola",
    "lychee", "rambutan", "longan", "durian", "jackfruit", "breadfruit",
    "persimmon", "pomelo", "custard apple", "soursop", "cherimoya",
    "elderberry", "mulberry", "acai berry", "goji berry", "currant",
    "boysenberry", "loganberry", "cloudberry", "huckleberry", "juniper berry",
    "sea buckthorn", "quince", "medlar", "jujube", "tamarind",
    "cactus fruit", "prickly pear", "plantain", "breadnut", "sapodilla",
    "mamey", "ackee", "miracle fruit", "horned melon", "physalis",
  ],
  "Vegetables": [
    "vegetables", "fresh vegetables", "leafy greens", "root vegetables",
    "cruciferous vegetables", "nightshade vegetables", "legumes", "pods",
    "carrot", "baby carrot", "purple carrot", "potato", "sweet potato",
    "russet potato", "red potato", "yukon potato", "fingerling potato",
    "onion", "red onion", "white onion", "yellow onion", "green onion",
    "scallion", "shallot", "leek", "chive", "tomato", "cherry tomato",
    "grape tomato", "roma tomato", "beefsteak tomato", "heirloom tomato",
    "spinach", "baby spinach", "arugula", "rocket", "lettuce", "romaine",
    "iceberg lettuce", "butter lettuce", "mixed greens", "kale",
    "collard greens", "mustard greens", "turnip greens", "chard",
    "swiss chard", "broccoli", "broccolini", "cauliflower", "brussels sprouts",
    "cabbage", "red cabbage", "napa cabbage", "bok choy", "chinese cabbage",
    "peas", "green peas", "snow peas", "snap peas", "sugar snap peas",
    "edamame", "lima beans", "green beans", "string beans", "wax beans",
    "garlic", "elephant garlic", "garlic scapes", "ginger", "fresh ginger",
    "galangal", "turmeric", "horseradish", "wasabi", "okra", "lady finger",
    "beetroot", "red beets", "golden beets", "chioggia beets", "beet greens",
    "radish", "daikon radish", "watermelon radish", "turnip", "rutabaga",
    "parsnip", "celery", "celery root", "celeriac", "fennel", "bulb fennel",
    "zucchini", "yellow squash", "summer squash", "winter squash",
    "butternut squash", "acorn squash", "spaghetti squash", "pumpkin",
    "kabocha squash", "delicata squash", "eggplant", "brinjal", "aubergine",
    "japanese eggplant", "chinese eggplant", "bell pepper", "red pepper",
    "yellow pepper", "orange pepper", "green pepper", "purple pepper",
    "chili pepper", "jalapeno", "serrano", "habanero", "poblano",
    "anaheim", "banana pepper", "sweet pepper", "hot pepper", "cayenne",
    "cucumber", "english cucumber", "persian cucumber", "pickling cucumber",
    "corn", "sweet corn", "corn on the cob", "baby corn", "artichoke",
    "jerusalem artichoke", "sunchoke", "asparagus", "green asparagus",
    "white asparagus", "purple asparagus", "mushroom", "button mushroom",
    "cremini", "portobello", "shiitake", "oyster mushroom", "enoki",
    "maitake", "morel", "chanterelle", "porcini", "truffle", "seaweed",
    "nori", "kelp", "wakame", "dulse", "sea lettuce", "sprouts",
    "bean sprouts", "alfalfa sprouts", "broccoli sprouts", "microgreens",
  ],
  "Hobbies and Crafts": [
    "hobbies", "hobby", "pastime", "leisure", "recreation", "crafts",
    "crafting", "handicraft", "handmade",
    "creativity", "art", "fine art",
    "visual art", "painting", "oil painting", "watercolor", "acrylic",
    "gouache", "tempera", "fresco", "mural", "canvas", "easel",
    "brush", "palette", "pigment", "drawing", "sketching", "pencil drawing",
    "charcoal",
    "digital art", "concept art", "portrait", "landscape",
    "sculpture", "clay", "pottery",
    "stoneware", "earthenware", "raku", "woodworking", "carpentry",
    "joinery", "furniture making", "woodturning", "whittling", "carving",
    "wood burning", "pyrography", "lumber", "hardwood", "softwood",
    "photography", "digital photography", "film photography", "camera",
    "portrait photography", "landscape photography", "macro photography",
    "street photography", "wildlife photography", "wedding photography",
    "knitting", "crocheting", "yarn", "wool", "cotton", "silk",
    "needle", "hook", "pattern", "stitch", "cable knit", "fair isle",
    "intarsia", "lace knitting", "embroidery", "cross stitch",
    "needlepoint", "tapestry", "quilting", "patchwork", "applique",
    "fabric", "thread", "sewing", "tailoring", "dressmaking",
    "sewing machine", "serger", "overlock", "pattern making",
    "gardening", "horticulture", "landscaping", "plant care", "greenhouse",
    "hydroponics", "aquaponics", "permaculture", "organic gardening",
    "vegetable garden", "flower garden", "herb garden", "indoor plants",
    "houseplants", "succulent", "cactus", "bonsai", "topiary",
    "pruning", "grafting", "propagation", "seed starting", "composting",
    "collecting", "collection", "antiques", "vintage", "memorabilia",
    "stamps", "coins", "cards", "toys", "books", "records",
    "vinyl", "model building", "scale model", "plastic model",
    "model train", "model airplane", "model car", "miniature",
    "diorama", "fishing", "angling", "fly fishing", "bait fishing",
    "rod", "reel", "tackle", "lure", "bait", "catch and release",
    "hiking", "trekking", "backpacking", "camping", "outdoors",
    "nature", "trail", "mountain",
    "bushcraft", "foraging", "bird watching", "birdwatching", "ornithology",
    "binoculars", "field guide", "nature photography", "astronomy",
    "stargazing", "telescope", "constellation", "planet", "meteor",
    "astrophotography", "chess", "board games", "card games", "puzzle",
    "crossword", "sudoku", "jigsaw puzzle", "rubiks cube", "magic",
    "illusion", "sleight of hand", "card tricks", "coin tricks",
    "juggling", "yo-yo", "origami", "paper folding", "kirigami",
    "paper craft", "scrapbooking", "card making", "bookbinding",
    "calligraphy", "lettering", "typography", "fountain pen", "ink",
    "parchment", "vellum", "manuscript", "journaling", "diary",
    "creative writing", "poetry", "storytelling", "blogging",
  ],
  "Anime and Manga": [
    "anime", "manga", "japanese animation", "japanese comics", "otaku",
    "weeb", "weeaboo", "japan", "japanese culture", "anime series",
    "anime movie", "anime film", "ova", "original video animation",
    "ona", "original net animation", "light novel", "visual novel",
    "shonen", "shojo", "seinen", "josei", "kodomomuke", "mecha",
    "isekai", "slice of life", "romance", "comedy", "drama", "action",
    "adventure", "fantasy", "sci-fi", "science fiction", "horror",
    "thriller", "mystery", "supernatural", "magical girl", "mahou shoujo",
    "sports anime", "school anime", "harem", "reverse harem", "yaoi",
    "yuri", "ecchi", "hentai", "doujinshi", "fan art", "fanfiction",
    "cosplay", "costume play", "convention", "anime convention", "con",
    "comic con", "anime expo", "comiket", "studio ghibli", "miyazaki",
    "toei animation", "madhouse", "pierrot", "bones", "mappa",
    "wit studio", "a-1 pictures", "shaft", "kyoto animation", "trigger",
    "gainax", "sunrise", "crunchyroll", "funimation", "viz media",
    "anime character", "protagonist", "antagonist", "tsundere", "yandere",
    "kuudere", "dandere", "loli", "shota", "senpai", "kohai",
    "sensei", "sama", "chan", "kun", "san", "chibi", "kawaii",
    "moe", "bishonen", "bishojo", "waifu", "husbando", "shipping",
    "otp", "one true pairing", "anime merchandise", "figure",
    "figurine", "nendoroid", "plushie", "poster", "keychain",
    "dakimakura", "body pillow", "anime music", "opening", "ending",
    "ost", "original soundtrack", "j-pop", "j-rock", "vocaloid",
    "hatsune miku", "karaoke", "anime fan", "anime culture", "weeb culture",
    "japanese language", "subtitles", "dub", "sub vs dub", "seiyuu",
    "voice actor", "voice actress", "japanese voice acting", "studio",
    "animation studio", "director", "animator", "mangaka", "author",
    "creator", "serialization", "weekly shonen jump", "shonen magazine",
    "weekly young jump", "big comic", "manga volume", "tankobon",
    "chapter", "one shot", "pilot", "cancelled", "hiatus", "completed",
    "ongoing", "adaptation", "live action", "netflix adaptation",
  ],
  "Gaming": [
    "gaming", "video games", "computer games", "console games", "mobile games",
    "pc games", "pc gaming", "console gaming", "mobile gaming", "handheld gaming",
    "retro gaming", "indie gaming", "aaa games", "triple a", "game development",
    "game design", "game developer", "game studio", "publisher", "platform",
    "steam", "epic games", "origin", "uplay", "gog", "itch.io",
    "console", "gaming console", "xbox", "xbox series x", "xbox series s",
    "xbox one", "xbox 360", "playstation", "ps5", "ps4", "ps3",
    "ps2", "ps1", "psx", "nintendo", "nintendo switch", "nintendo 3ds",
    "nintendo ds", "wii", "wii u", "gamecube", "n64", "snes", "nes",
    "game boy", "game boy advance", "psp", "ps vita", "steam deck",
    "gpu", "graphics card", "cpu", "processor", "ram", "memory",
    "ssd", "hard drive", "cooling", "overclocking", "fps", "frames per second",
    "resolution", "4k", "1440p", "1080p", "refresh rate", "144hz",
    "60hz", "vsync", "gsync", "freesync", "ray tracing", "dlss",
    "esports", "e-sports", "competitive gaming", "tournament", "league",
    "championship", "professional gaming", "pro gamer", "streamer",
    "content creator", "twitch", "youtube gaming", "facebook gaming",
    "streaming", "live streaming", "obs", "gameplay", "walkthrough",
    "playthrough", "lets play", "speedrun", "any percent", "world record",
    "personal best", "pb", "wr", "leaderboard", "ranking", "matchmaking",
    "mmr", "matchmaking rating", "elo", "skill rating", "casual",
    "ranked", "competitive", "ladder", "season", "battle pass",
    "dlc", "downloadable content", "expansion", "patch", "update",
    "hotfix", "nerf", "buff", "balance", "meta", "metagame",
    "tier list", "op",
    "genre", "action", "adventure", "rpg", "role playing game",
    "jrpg", "japanese rpg", "mmorpg", "massively multiplayer online",
    "fps", "first person shooter", "tps", "third person shooter",
    "battle royale", "moba", "multiplayer online battle arena",
    "rts", "real time strategy", "turn based strategy", "4x",
    "city builder", "simulation", "racing", "fighting", "platformer",
    "puzzle", "horror", "survival", "sandbox", "open world",
    "linear", "semi open world", "roguelike", "roguelite", "souls like",
    "metroidvania", "visual novel", "dating sim", "rhythm game",
    "music game", "sports game", "party game", "co-op", "cooperative",
    "single player", "multiplayer", "local multiplayer", "online multiplayer",
    "cross platform", "cross play", "modding", "mod", "modification",
    "community", "guild", "clan", "team", "squad", "party",
    "voice chat", "text chat", "discord", "teamspeak", "ventrilo",
    "achievement", "trophy", "badge", "collectible", "easter egg",
    "secret", "hidden", "unlock", "progression", "level up",
    "experience", "xp", "skill tree", "talent", "ability", "power up",
    "item", "equipment", "gear", "weapon", "armor", "consumable",
    "inventory", "crafting", "recipe", "material", "resource",
    "currency", "gold", "coins", "gems", "premium currency",
    "microtransaction", "pay to win", "p2w", "free to play", "f2p",
    "gacha", "loot box", "random", "rng",

  ],
  "Movies and Entertainment": [
    "movies", "films", "cinema", "movie theater", "theatre", "screening",
    "premiere", "box office", "blockbuster", "indie film", "independent film",
    "art film", "documentary", "mockumentary", "biopic", "biographical",
    "drama", "comedy", "romantic comedy", "rom com", "action", "adventure",
    "thriller", "suspense", "horror", "slasher", "psychological horror",
    "sci-fi", "science fiction", "fantasy", "superhero", "western",
    "war film", "historical", "period piece", "musical", "animated",
    "animation", "stop motion", "cgi", "computer generated imagery",
    "3d", "imax", "dolby atmos", "surround sound", "director", "filmmaker",
    "auteur", "producer", "executive producer", "screenwriter", "script",
    "screenplay", "cinematographer", "editor", "composer", "score",
    "soundtrack", "theme song", "actors", "actress", "cast", "ensemble",
    "leading role", "supporting role", "cameo", "method acting",
    "performance", "oscar", "academy award", "golden globe", "bafta",
    "cannes", "sundance", "film festival", "critics", "review",
    "rating", "rotten tomatoes", "imdb", "metacritic", "box office",
    "opening weekend", "gross", "budget", "profit", "flop", "cult classic",
    "franchise", "sequel", "prequel", "reboot", "remake", "adaptation",
    "book adaptation", "comic book movie", "superhero movie", "marvel",
    "dc", "disney", "pixar", "dreamworks", "warner bros", "universal",
    "paramount", "sony", "20th century fox", "mgm", "streaming",
    "netflix", "amazon prime", "hulu", "disney plus", "hbo max",
    "apple tv", "paramount plus", "peacock", "tv series", "television",
    "tv show", "series", "season", "episode", "pilot", "finale",
    "cliffhanger", "binge watching", "marathon", "web series", "miniseries",
    "limited series", "anthology", "sitcom", "drama series", "reality tv",
    "talk show", "game show", "news", "documentary series", "true crime",
    "cooking show", "travel show", "nature documentary", "bollywood",
    "hollywood", "nollywood", "korean cinema", "french cinema",
    "italian cinema", "japanese cinema", "chinese cinema", "world cinema",
    "foreign film", "subtitles", "dubbing", "voice over", "narrator",
    "genre", "subgenre", "trope", "cliche", "plot twist", "spoiler",
    "spoiler alert", "trailer", "teaser", "poster", "promotional",
    "marketing", "viral marketing", "fan theory", "easter egg",
    "reference", "homage", "parody", "satire", "spoof", "comedy",
    "stand up comedy", "improv", "sketch comedy", "variety show",
  ],
  "Music": [
    "music", "song", "track", "album", "ep", "extended play", "single",
    "compilation", "greatest hits", "live album", "studio album",
    "concept album", "soundtrack", "remix", "cover",
    "acoustic", "concert", "performance", "gig",
    "show", "music festival",
    "musician", "artist", "band", "solo artist", "singer",
    "vocalist", "songwriter", "composer", "lyricist", "producer",
    "sound engineer",
    "rock", "pop", "hip hop", "rap", "r&b", "soul", "funk",
    "jazz", "blues", "country music", "folk", "classical", "opera",
    "electronic", "edm", "techno", "trance", "dubstep",
    "drum and bass", "avant garde", "punk", "metal", "heavy metal", "death metal", "black metal",
    "thrash metal", "progressive", "indie", "alternative", "grunge",
    "britpop", "new wave", "post punk", "shoegaze", "dream pop",
    "psychedelic", "garage", "surf", "rockabilly", "ska", "reggae",
    "dub", "dancehall", "afrobeat", "latin", "salsa", "merengue",
    "bachata", "tango", "flamenco", "bossa nova", "samba", "fado",
    "celtic", "traditional", "world music", "fusion", "crossover",
    "instrument", "guitar", "electric guitar", "acoustic guitar",
    "bass", "bass guitar", "drums", "drum kit", "percussion",
    "piano", "synthesizer", "organ", "violin", "viola",
    "cello", "double bass", "trumpet", "trombone", "saxophone",
    "clarinet", "flute", "oboe", "french horn", "tuba", "harmonica",
    "banjo", "mandolin", "ukulele", "accordion", "bagpipes",
    "singing", "vocals", "harmony", "melody", "rhythm", "beat",
    "tempo", "time signature", "key", "chord", "progression",
    "scale", "arpeggio", "riff", "lick", "solo",
    "chorus", "verse", "refrain", "hook", "motif", "theme",
    "lyrics", "songwriting", "poetry", "rhyme", "meter", "verse",
    "playlist", "mixtape", "setlist", "encore",
    "jam", "improvisation", "duet", "spotify", "apple music", "youtube music",
    "soundcloud", "bandcamp", "pandora", "radio", "podcast",
    "streaming", "record", "cd", "cassette",
    "mp3", "flac", "wav", "lossless", "audiophile",
    "sound quality", "hi-fi", "stereo", "mono", "surround sound",
    "headphones", "earbuds", "speakers", "amplifier", "equalizer",
    "turntable", "record player", "cd player", "boom box", "walkman",
    "ipod", "music video", "mtv", "vevo", "choreography", "dance",
    "awards", "grammy", "chart", "hit",
    "fandom", "stan",
    "open mic", "karaoke", "sing along", "music theory", "talent show",
  ],
  "Cryptocurrency": [
    "blockchain", "bitcoin", "ethereum", "altcoin", "smart contracts", "defi", "nft", "wallet", "private key", "public key", "gas fees", "mining", "proof of work", "proof of stake", "exchange", "token", "stablecoin", "hash rate", "cold storage", "ledger", "fork",
    "airdrop", "ico", "web3", "dao", "btc", "eth", "bnb", "xrp", "sol", "ada", "doge", "shib", "dot", "matic", "ltc", "avax", "uni", "link", "trx", "atom", "xlm", "apt", "near", "algo",
  ],
  "Countries": [
    "united states", "usa", "us", "america", "united states of america",
    "canada", "mexico", "brazil", "argentina", "chile", "colombia", "peru",
    "venezuela", "ecuador", "bolivia", "paraguay", "uruguay", "guyana",
    "suriname", "french guiana", "united kingdom", "uk", "great britain",
    "england", "scotland", "wales", "northern ireland", "ireland", "france",
    "germany", "italy", "spain", "portugal", "netherlands", "belgium",
    "switzerland", "austria", "poland", "czech republic", "slovakia",
    "hungary", "romania", "bulgaria", "greece", "croatia", "serbia",
    "bosnia", "montenegro", "albania", "macedonia", "slovenia", "denmark",
    "sweden", "norway", "finland", "iceland", "estonia", "latvia",
    "lithuania", "russia", "ukraine", "belarus", "moldova", "georgia",
    "armenia", "azerbaijan", "kazakhstan", "uzbekistan", "turkmenistan",
    "kyrgyzstan", "tajikistan", "afghanistan", "pakistan", "india",
    "bangladesh", "sri lanka", "maldives", "nepal", "bhutan", "myanmar",
    "thailand", "vietnam", "laos", "cambodia", "malaysia", "singapore",
    "indonesia", "brunei", "philippines", "china", "japan", "south korea",
    "north korea", "mongolia", "taiwan", "hong kong", "macau", "turkey",
    "cyprus", "syria", "lebanon", "israel", "palestine", "jordan",
    "iraq", "iran", "saudi arabia", "yemen", "oman", "uae", "qatar",
    "bahrain", "kuwait", "egypt", "libya", "tunisia", "algeria", "morocco",
    "sudan", "south sudan", "ethiopia", "eritrea", "djibouti", "somalia",
    "kenya", "uganda", "tanzania", "rwanda", "burundi", "democratic republic of congo",
    "central african republic", "chad", "cameroon", "equatorial guinea",
    "gabon", "republic of congo", "angola", "zambia", "zimbabwe", "botswana",
    "namibia", "south africa", "lesotho", "swaziland", "mozambique",
    "madagascar", "mauritius", "comoros", "seychelles", "mali", "burkina faso",
    "niger", "nigeria", "benin", "togo", "ghana", "ivory coast", "liberia",
    "sierra leone", "guinea", "guinea bissau", "senegal", "mauritania",
    "cape verde", "gambia", "australia", "new zealand", "papua new guinea",
    "fiji", "solomon islands", "vanuatu", "samoa", "tonga", "kiribati",
    "tuvalu", "nauru", "palau", "marshall islands", "micronesia",
  ],
  "Continents": [
    "africa", "african continent", "dark continent", "motherland", "cradle of humanity",
    "asia", "asian continent", "orient", "far east", "middle east", "south asia",
    "southeast asia", "central asia", "east asia", "western asia",
    "europe", "european continent", "old continent", "western europe",
    "eastern europe", "northern europe", "southern europe", "central europe",
    "scandinavia", "balkans", "iberian peninsula", "british isles",
    "north america", "north american continent", "northern america",
    "south america", "south american continent", "latin america",
    "americas", "new world", "western hemisphere",
    "antarctica", "antarctic continent", "south pole", "frozen continent",
    "australia", "oceania", "australasia", "pacific islands", "down under",
    "continental drift", "pangaea", "gondwana", "laurasia", "tectonic plates",
    "landmass", "continental shelf", "subcontinent", "transcontinental",
    "intercontinental", "pan-african", "pan-american", "eurasian",
    "afro-eurasia", "eurasia", "indo-pacific", "atlantic world",
  ],
  "Culture": [
    "western culture", "eastern culture", "oriental culture", "occidental culture",
    "american culture", "european culture", "asian culture", "african culture",
    "indigenous culture", "native culture", "aboriginal culture", "tribal culture",
    "ancient culture", "classical culture", "medieval culture", "renaissance culture",
    "modern culture", "contemporary culture", "pop culture", "popular culture",
    "youth culture", "counterculture", "subculture", "mainstream culture",
    "high culture", "low culture", "elite culture", "mass culture",
    "urban culture", "rural culture", "metropolitan culture", "cosmopolitan culture",
    "multicultural", "cross-cultural", "intercultural", "cultural exchange",
    "cultural diversity", "cultural heritage", "cultural identity", "cultural values",
    "cultural norms", "cultural practices", "cultural traditions", "cultural customs",
    "cultural beliefs", "cultural expression", "cultural art", "cultural music",
    "cultural dance", "cultural food", "cultural cuisine", "cultural language",
    "cultural dialect", "cultural festival", "cultural celebration", "cultural ritual",
    "cultural ceremony", "cultural symbols", "cultural artifacts", "cultural legacy",
    "cultural preservation", "cultural transmission", "cultural adaptation",
    "cultural assimilation", "cultural integration", "cultural fusion",
    "cultural appropriation", "cultural sensitivity", "cultural awareness",
    "cultural competence", "cultural literacy", "cultural studies", "anthropology",
    "ethnography", "folklore", "mythology", "oral tradition", "storytelling",
    "proverbs", "folktales", "legends", "myths", "epic tales", "cultural narrative",
    "social customs", "etiquette", "manners", "protocols", "behavioral norms",
    "social roles", "family structure", "kinship", "community", "tribe",
    "clan", "ethnic group", "ethnicity", "nationality", "citizenship",
    "diaspora", "migration", "immigration", "emigration", "cultural diffusion",
    "globalization", "westernization", "modernization", "traditionalism",
    "conservatism", "progressivism", "liberalism", "fundamentalism",
    "secularism", "spirituality", "religiosity", "faith", "belief system",
    "worldview", "philosophy", "ideology", "doctrine", "creed", "dogma",
    "cultural relativism", "cultural universalism", "cultural determinism",
    "cultural materialism", "cultural evolution", "cultural revolution",
    "cultural renaissance", "cultural revival", "cultural decline",
    "cultural crisis", "cultural conflict", "cultural clash", "culture war",
    "cultural hegemony", "cultural imperialism", "cultural colonialism",
    "decolonization", "cultural independence", "cultural sovereignty",
    "cultural nationalism", "cultural patriotism", "cultural pride",
    "cultural shame", "cultural trauma", "cultural memory", "collective memory",
    "cultural continuity", "cultural change", "cultural transformation",
    "cultural innovation", "cultural creativity", "cultural expression",
    "cultural production", "cultural consumption", "cultural capital",
    "cultural economy", "cultural industry", "cultural market", "cultural goods",
    "cultural services", "cultural tourism", "cultural diplomacy",
    "cultural exchange program", "cultural ambassador", "cultural bridge",
    "cultural barrier", "cultural gap", "cultural divide", "cultural unity",
    "cultural harmony", "cultural peace", "cultural understanding",
    "cultural tolerance", "cultural respect", "cultural appreciation",
  ],
  "Seven Wonders": [
    // Ancient Seven Wonders
    "seven wonders", "seven wonders of the world", "ancient seven wonders",
    "great pyramid", "great pyramid of giza", "pyramid of khufu", "pyramid of cheops",
    "hanging gardens", "hanging gardens of babylon", "gardens of babylon",
    "statue of zeus", "statue of zeus at olympia", "zeus at olympia",
    "temple of artemis", "temple of artemis at ephesus", "artemis at ephesus",
    "mausoleum", "mausoleum at halicarnassus", "mausoleum of halicarnassus",
    "colossus", "colossus of rhodes", "rhodes colossus",
    "lighthouse of alexandria", "pharos", "pharos of alexandria",

    // New Seven Wonders
    "new seven wonders", "new 7 wonders", "modern seven wonders",
    "great wall", "great wall of china", "chinese wall", "wall of china",
    "petra", "rose city", "lost city of petra", "nabataean city",
    "christ the redeemer", "christ statue", "cristo redentor", "rio christ",
    "machu picchu", "lost city of incas", "inca citadel", "inca ruins",
    "chichen itza", "mayan ruins", "el castillo", "kukulcan pyramid",
    "colosseum", "roman colosseum", "flavian amphitheatre", "gladiator arena",
    "taj mahal", "crown of palaces", "taj", "mausoleum of mumtaz",

    // Natural Seven Wonders
    "natural seven wonders", "natural wonders", "seven natural wonders",
    "grand canyon", "colorado canyon", "grand canyon national park",
    "mount everest", "everest", "sagarmatha", "chomolungma", "highest peak",
    "victoria falls", "mosi-oa-tunya", "smoke that thunders", "zambezi falls",
    "great barrier reef", "coral reef", "australian reef", "barrier reef",
    "northern lights", "aurora borealis", "polar lights", "aurora",
    "paricutin volcano", "paricutin", "mexican volcano", "cinder cone",
    "harbor of rio", "guanabara bay", "rio de janeiro harbor", "rio harbor",

    // UNESCO World Heritage Sites
    "world heritage", "unesco world heritage", "heritage site", "cultural heritage",
    "natural heritage", "world heritage site", "protected site", "unesco site",
    "cultural landscape", "archaeological site", "historic site", "monument",
    "historic center", "old city", "ancient city", "ruins", "archaeological ruins",
    "cathedral", "basilica", "church", "monastery", "temple", "mosque",
    "palace", "castle", "fortress", "citadel", "fort", "defensive wall",
    "national park", "nature reserve", "protected area", "biosphere reserve",
    "marine park", "coral reef system", "wetland", "forest", "mountain range",
    "geological formation", "fossil site", "cave system", "canyon", "waterfall",

    // Modern Architectural Wonders
    "modern wonders", "architectural wonders", "engineering marvels",
    "burj khalifa", "tallest building", "dubai tower", "khalifa tower",
    "eiffel tower", "iron lady", "tour eiffel", "paris tower",
    "empire state building", "esb", "new york skyscraper", "art deco building",
    "golden gate bridge", "san francisco bridge", "suspension bridge",
    "sydney opera house", "opera house", "performing arts center",
    "sagrada familia", "gaudi cathedral", "barcelona cathedral", "holy family",
    "st basils cathedral", "red square cathedral", "onion domes", "moscow cathedral",
    "neuschwanstein castle", "fairy tale castle", "bavarian castle", "disney castle",
    "angkor wat", "angkor complex", "khmer temple", "cambodian temple",
    "borobudur", "buddhist temple", "java temple", "indonesian temple",
    "stonehenge", "stone circle", "megalithic monument", "prehistoric monument",
    "easter island", "moai statues", "rapa nui", "stone heads",
    "acropolis", "parthenon", "ancient athens", "greek temple",
    "forbidden city", "imperial palace", "beijing palace", "chinese palace",
    "kremlin", "moscow kremlin", "red square", "russian fortress",
    "alhambra", "moorish palace", "granada palace", "islamic architecture",
    "mont saint michel", "abbey", "tidal island", "normandy abbey",
    "tower bridge", "london bridge", "thames bridge", "bascule bridge",
    "statue of liberty", "liberty enlightening the world", "lady liberty",
    "mount rushmore", "presidents mountain", "carved faces", "south dakota monument",
    "CN tower", "toronto tower", "communications tower", "canadian tower",
    "space needle", "seattle tower", "observation tower", "world fair tower",
    "willis tower", "sears tower", "chicago skyscraper", "tallest in america",
    "one world trade center", "freedom tower", "wtc", "ground zero tower",
    "pantheon", "roman temple", "concrete dome", "ancient rome",
    "hagia sophia", "holy wisdom", "byzantine cathedral", "istanbul mosque",
    "notre dame", "notre dame cathedral", "paris cathedral", "gothic cathedral",
    "westminster abbey", "coronation church", "london abbey", "royal church",
    "st peters basilica", "vatican basilica", "papal basilica", "sistine chapel",
    "dome of the rock", "jerusalem shrine", "islamic shrine", "golden dome",
    "wailing wall", "western wall", "kotel", "temple mount wall",
    "mecca", "kaaba", "holy mosque", "pilgrimage site", "islamic holy site",
    "vatican city", "papal state", "holy see", "smallest country",
    "lourdes", "pilgrimage site", "marian shrine", "healing waters",
    "santiago de compostela", "camino", "pilgrimage route", "way of st james",
  ],
  "Banking": [
    "bank", "banking", "savings account", "checking account", "interest rate",
    "fixed deposit", "recurring deposit", "loan", "home loan", "car loan",
    "personal loan", "net banking", "mobile banking", "atm", "cheque",
    "debit card", "credit card", "bank statement", "ifsc code",
  ],

  "Career": [
    "career", "job", "interview", "resume", "cv", "cover letter", "job search",
    "linkedin", "networking", "freelance", "remote work", "promotion",
    "internship", "job offer", "salary negotiation", "career growth",
    "mentorship", "recruitment", "headhunter",
  ],

  "Daily Life": [
    "routine", "morning routine", "chores", "daily tasks", "home", "commute",
    "errands", "time management", "work life", "day to day", "lifestyle",
  ],

  "Economy": [
    "economy", "gdp", "inflation", "deflation", "recession", "economic growth",
    "unemployment", "macroeconomics", "microeconomics", "fiscal policy",
    "monetary policy", "interest rate", "economic indicator",
  ],

  "Finance": [
    "finance", "budget", "income", "expense", "savings", "debt", "investment",
    "assets", "liabilities", "financial planning", "net worth", "emergency fund",
    "credit score", "compound interest",
  ],

  "Financial Markets": [
    "stock market", "share", "stock", "bond", "mutual fund", "index",
    "sensex", "nifty", "nasdaq", "dow jones", "bull market", "bear market",
    "ipo", "dividend", "portfolio", "broker", "trading", "investor",
  ],

  "Inspiration": [
    "inspire", "inspiration", "role model", "vision", "goal", "achievement",
    "dream", "greatness", "success story", "life lesson", "legacy", "ambition",
  ],

  "Investing": [
    "investing", "investment", "stocks", "mutual funds", "real estate",
    "etf", "bonds", "roth ira", "401k", "sip", "diversification", "risk",
    "return", "capital gain", "long term", "short term", "investment strategy",
  ],

  "Mental Health": [
    "mental health", "anxiety", "depression", "therapy", "counseling", "mindfulness",
    "stress", "trauma", "meditation", "psychology", "wellbeing", "mental illness",
    "burnout", "self care", "emotional health",
  ],

  "Motivation": [
    "motivation", "motivated", "goal", "drive", "focus", "discipline", "willpower",
    "grit", "self discipline", "ambition", "success", "inspiration", "overcome",
  ],

  "News": [
    "news", "headline", "breaking news", "latest update", "news report",
    "news article", "press", "media", "journalism", "current affairs", "trending",
  ],

  "Parenting": [
    "parent", "parenting", "mother", "father", "mom", "dad", "childcare",
    "discipline", "schooling", "baby", "toddler", "teenager", "child",
    "parenthood", "raising kids", "family",
  ],

  "Personal Finance": [
    "personal finance", "budget", "spending", "saving", "emergency fund",
    "debt", "credit card", "loan", "finance goal", "financial independence",
    "retirement planning", "monthly budget",
  ],

  "Philosophy": [
    "philosophy", "stoicism", "existentialism", "nihilism", "ethics",
    "morality", "truth", "reality", "logic", "socrates", "plato", "aristotle",
    "mind", "being", "meaning of life",
  ],

  "Productivity": [
    "productivity", "efficient", "focus", "pomodoro", "to-do list", "planner",
    "time block", "task management", "habit", "routine", "goal setting",
    "workflow", "procrastination",
  ],

  "Relationships": [
    "relationship", "love", "romance", "dating", "breakup", "marriage",
    "trust", "communication", "intimacy", "partner", "connection", "bond",
    "friendship", "empathy",
  ],

  "Science": [
    "science", "experiment", "biology", "physics", "chemistry", "astronomy",
    "research", "scientific method", "theory", "hypothesis", "laboratory",
    "discovery", "scientist",
  ],

  "Self Improvement": [
    "self improvement", "self growth", "personal growth", "habit", "discipline",
    "confidence", "resilience", "self awareness", "goal", "mindset", "reflection",
  ],

  "Spirituality": [
    "spirituality", "soul", "energy", "meditation", "consciousness", "karma",
    "awakening", "chakras", "healing", "yoga", "nirvana", "inner peace",
    "faith", "divine",
  ],

  "Technology Trends": [
    "tech trend", "ai", "ml", "blockchain", "iot", "5g", "metaverse",
    "web3", "cloud computing", "automation", "robotics", "edge computing",
    "digital transformation",
  ],

  "Travel": [
    "travel", "trip", "vacation", "tourism", "flight", "hotel", "itinerary",
    "explore", "passport", "visa", "backpacking", "destination", "tourist",
    "adventure", "road trip",
  ],
};


module.exports = tagKeywords;
