# Configuration file for blog tagging model

# Available tags for the model
AVAILABLE_TAGS = [
    "API", "Anime and Manga", "Artificial Intelligence", "Augmented Reality Virtual Reality",
    "Backend", "Blockchain", "Career", "Cloud Computing", "Continents", "Countries",
    "CSS", "Cryptocurrency", "Cuisine", "Culture", "Daily Life", "Database",
    "DevOps", "Education and Learning", "Environment and Sustainability", "Food and Cooking",
    "Framework", "Frontend", "Fruits", "Gaming", "Health and Fitness", "History",
    "Hobbies and Crafts", "Inspiration", "JavaScript", "Mental Health", "Mobile",
    "Motivation", "Movies and Entertainment", "Music", "News", "Parenting",
    "Performance", "Personal Finance", "Philosophy", "Planets and Stars", "Productivity",
    "Programming Languages", "Quantum Computing", "React", "Relationships", "Science",
    "Security", "Self Improvement", "Seven Wonders", "Software Architecture", "Space",
    "Spirituality", "Technology Trends", "Testing", "Travel", "Tutorial",
    "Vegetables", "Web Development", "Wildlife"
]

# Programming languages mapping
PROGRAMMING_LANGUAGES = {
    'python': 'Programming Languages',
    'javascript': 'Programming Languages',
    'js': 'Programming Languages',
    'java': 'Programming Languages',
    'cpp': 'Programming Languages',
    'c++': 'Programming Languages',
    'csharp': 'Programming Languages',
    'c#': 'Programming Languages',
    'php': 'Programming Languages',
    'ruby': 'Programming Languages',
    'go': 'Programming Languages',
    'rust': 'Programming Languages',
    'swift': 'Programming Languages',
    'kotlin': 'Programming Languages',
    'scala': 'Programming Languages',
    'perl': 'Programming Languages',
    'r': 'Programming Languages',
    'matlab': 'Programming Languages',
    'sql': 'Programming Languages',
    'typescript': 'Programming Languages',
    'dart': 'Programming Languages',
    'elixir': 'Programming Languages',
    'clojure': 'Programming Languages',
    'haskell': 'Programming Languages',
    'lua': 'Programming Languages',
    'assembly': 'Programming Languages',
    'fortran': 'Programming Languages',
    'cobol': 'Programming Languages'
}

# Countries mapping
COUNTRIES = {
    'usa': 'Countries', 'america': 'Countries', 'united states': 'Countries',
    'uk': 'Countries', 'britain': 'Countries', 'england': 'Countries', 'united kingdom': 'Countries',
    'india': 'Countries', 'bharat': 'Countries',
    'china': 'Countries', 'prc': 'Countries',
    'japan': 'Countries', 'nippon': 'Countries',
    'germany': 'Countries', 'deutschland': 'Countries',
    'france': 'Countries', 'francia': 'Countries',
    'russia': 'Countries', 'ussr': 'Countries',
    'canada': 'Countries',
    'australia': 'Countries',
    'brazil': 'Countries', 'brasil': 'Countries',
    'mexico': 'Countries',
    'italy': 'Countries', 'italia': 'Countries',
    'spain': 'Countries', 'espana': 'Countries',
    'south korea': 'Countries', 'korea': 'Countries',
    'netherlands': 'Countries', 'holland': 'Countries',
    'sweden': 'Countries',
    'norway': 'Countries',
    'denmark': 'Countries',
    'finland': 'Countries',
    'switzerland': 'Countries',
    'austria': 'Countries',
    'belgium': 'Countries',
    'portugal': 'Countries',
    'greece': 'Countries',
    'turkey': 'Countries',
    'egypt': 'Countries',
    'nigeria': 'Countries',
    'south africa': 'Countries',
    'kenya': 'Countries',
    'argentina': 'Countries',
    'chile': 'Countries',
    'colombia': 'Countries',
    'peru': 'Countries',
    'venezuela': 'Countries',
    'thailand': 'Countries',
    'vietnam': 'Countries',
    'indonesia': 'Countries',
    'malaysia': 'Countries',
    'singapore': 'Countries',
    'philippines': 'Countries',
    'bangladesh': 'Countries',
    'pakistan': 'Countries',
    'sri lanka': 'Countries',
    'nepal': 'Countries',
    'afghanistan': 'Countries',
    'iran': 'Countries',
    'iraq': 'Countries',
    'israel': 'Countries',
    'saudi arabia': 'Countries',
    'uae': 'Countries',
    'kuwait': 'Countries',
    'qatar': 'Countries',
    'bahrain': 'Countries',
    'oman': 'Countries',
    'jordan': 'Countries',
    'lebanon': 'Countries',
    'syria': 'Countries',
    'morocco': 'Countries',
    'algeria': 'Countries',
    'tunisia': 'Countries',
    'libya': 'Countries',
    'sudan': 'Countries',
    'ethiopia': 'Countries',
    'ghana': 'Countries',
    'cameroon': 'Countries',
    'madagascar': 'Countries',
    'zimbabwe': 'Countries',
    'botswana': 'Countries',
    'namibia': 'Countries',
    'zambia': 'Countries',
    'uganda': 'Countries',
    'tanzania': 'Countries',
    'rwanda': 'Countries',
    'congo': 'Countries',
    'gabon': 'Countries',
    'angola': 'Countries',
    'mozambique': 'Countries',
    'malawi': 'Countries',
    'lesotho': 'Countries',
    'swaziland': 'Countries',
    'mauritius': 'Countries',
    'seychelles': 'Countries',
    'new zealand': 'Countries',
    'fiji': 'Countries',
    'papua new guinea': 'Countries',
    'samoa': 'Countries',
    'tonga': 'Countries',
    'vanuatu': 'Countries',
    'solomon islands': 'Countries',
    'palau': 'Countries',
    'micronesia': 'Countries',
    'marshall islands': 'Countries',
    'kiribati': 'Countries',
    'nauru': 'Countries',
    'tuvalu': 'Countries'
}

# Continents mapping
CONTINENTS = {
    'asia': 'Continents', 'asian': 'Continents',
    'europe': 'Continents', 'european': 'Continents',
    'africa': 'Continents', 'african': 'Continents',
    'north america': 'Continents', 'north american': 'Continents',
    'south america': 'Continents', 'south american': 'Continents',
    'australia': 'Continents', 'oceania': 'Continents', 'australian': 'Continents',
    'antarctica': 'Continents', 'antarctic': 'Continents'
}

# Seven Wonders mapping
SEVEN_WONDERS = {
    'great wall of china': 'Seven Wonders', 'china wall': 'Seven Wonders', 'great wall': 'Seven Wonders',
    'christ the redeemer': 'Seven Wonders', 'christ statue': 'Seven Wonders', 'redeemer statue': 'Seven Wonders',
    'machu picchu': 'Seven Wonders', 'inca city': 'Seven Wonders',
    'chichen itza': 'Seven Wonders', 'maya pyramid': 'Seven Wonders',
    'roman colosseum': 'Seven Wonders', 'colosseum': 'Seven Wonders', 'coliseum': 'Seven Wonders',
    'petra': 'Seven Wonders', 'rose city': 'Seven Wonders',
    'taj mahal': 'Seven Wonders'
}

# Fruits mapping
FRUITS = {
    'apple': 'Fruits', 'apples': 'Fruits',
    'banana': 'Fruits', 'bananas': 'Fruits',
    'orange': 'Fruits', 'oranges': 'Fruits',
    'grape': 'Fruits', 'grapes': 'Fruits',
    'strawberry': 'Fruits', 'strawberries': 'Fruits',
    'mango': 'Fruits', 'mangoes': 'Fruits',
    'pineapple': 'Fruits', 'pineapples': 'Fruits',
    'watermelon': 'Fruits', 'watermelons': 'Fruits',
    'peach': 'Fruits', 'peaches': 'Fruits',
    'pear': 'Fruits', 'pears': 'Fruits',
    'cherry': 'Fruits', 'cherries': 'Fruits',
    'plum': 'Fruits', 'plums': 'Fruits',
    'kiwi': 'Fruits', 'kiwis': 'Fruits',
    'lemon': 'Fruits', 'lemons': 'Fruits',
    'lime': 'Fruits', 'limes': 'Fruits',
    'coconut': 'Fruits', 'coconuts': 'Fruits',
    'avocado': 'Fruits', 'avocados': 'Fruits',
    'papaya': 'Fruits', 'papayas': 'Fruits',
    'pomegranate': 'Fruits', 'pomegranates': 'Fruits',
    'blueberry': 'Fruits', 'blueberries': 'Fruits',
    'raspberry': 'Fruits', 'raspberries': 'Fruits',
    'blackberry': 'Fruits', 'blackberries': 'Fruits',
    'cranberry': 'Fruits', 'cranberries': 'Fruits',
    'fig': 'Fruits', 'figs': 'Fruits',
    'date': 'Fruits', 'dates': 'Fruits',
    'apricot': 'Fruits', 'apricots': 'Fruits',
    'cantaloupe': 'Fruits', 'cantaloupes': 'Fruits',
    'honeydew': 'Fruits', 'honeydews': 'Fruits',
    'passion fruit': 'Fruits', 'passion fruits': 'Fruits',
    'dragon fruit': 'Fruits', 'dragon fruits': 'Fruits',
    'lychee': 'Fruits', 'lychees': 'Fruits',
    'rambutan': 'Fruits', 'rambutans': 'Fruits',
    'durian': 'Fruits', 'durians': 'Fruits',
    'jackfruit': 'Fruits', 'jackfruits': 'Fruits',
    'guava': 'Fruits', 'guavas': 'Fruits',
    'persimmon': 'Fruits', 'persimmons': 'Fruits',
    'pomelo': 'Fruits', 'pomelos': 'Fruits',
    'star fruit': 'Fruits', 'star fruits': 'Fruits',
    'elderberry': 'Fruits', 'elderberries': 'Fruits',
    'gooseberry': 'Fruits', 'gooseberries': 'Fruits',
    'currant': 'Fruits', 'currants': 'Fruits'
}

# Vegetables mapping
VEGETABLES = {
    'tomato': 'Vegetables', 'tomatoes': 'Vegetables',
    'potato': 'Vegetables', 'potatoes': 'Vegetables',
    'carrot': 'Vegetables', 'carrots': 'Vegetables',
    'onion': 'Vegetables', 'onions': 'Vegetables',
    'garlic': 'Vegetables',
    'lettuce': 'Vegetables',
    'spinach': 'Vegetables',
    'broccoli': 'Vegetables',
    'cauliflower': 'Vegetables',
    'cabbage': 'Vegetables',
    'cucumber': 'Vegetables', 'cucumbers': 'Vegetables',
    'pepper': 'Vegetables', 'peppers': 'Vegetables',
    'bell pepper': 'Vegetables', 'bell peppers': 'Vegetables',
    'celery': 'Vegetables',
    'asparagus': 'Vegetables',
    'zucchini': 'Vegetables',
    'eggplant': 'Vegetables', 'eggplants': 'Vegetables',
    'corn': 'Vegetables', 'maize': 'Vegetables',
    'peas': 'Vegetables', 'pea': 'Vegetables',
    'bean': 'Vegetables', 'beans': 'Vegetables',
    'mushroom': 'Vegetables', 'mushrooms': 'Vegetables',
    'radish': 'Vegetables', 'radishes': 'Vegetables',
    'beet': 'Vegetables', 'beets': 'Vegetables', 'beetroot': 'Vegetables',
    'turnip': 'Vegetables', 'turnips': 'Vegetables',
    'parsnip': 'Vegetables', 'parsnips': 'Vegetables',
    'sweet potato': 'Vegetables', 'sweet potatoes': 'Vegetables',
    'kale': 'Vegetables',
    'chard': 'Vegetables', 'swiss chard': 'Vegetables',
    'arugula': 'Vegetables', 'rocket': 'Vegetables',
    'watercress': 'Vegetables',
    'leek': 'Vegetables', 'leeks': 'Vegetables',
    'shallot': 'Vegetables', 'shallots': 'Vegetables',
    'scallion': 'Vegetables', 'scallions': 'Vegetables',
    'chive': 'Vegetables', 'chives': 'Vegetables',
    'basil': 'Vegetables',
    'parsley': 'Vegetables',
    'cilantro': 'Vegetables', 'coriander': 'Vegetables',
    'dill': 'Vegetables',
    'mint': 'Vegetables',
    'oregano': 'Vegetables',
    'thyme': 'Vegetables',
    'rosemary': 'Vegetables',
    'sage': 'Vegetables',
    'artichoke': 'Vegetables', 'artichokes': 'Vegetables',
    'fennel': 'Vegetables',
    'okra': 'Vegetables',
    'squash': 'Vegetables',
    'pumpkin': 'Vegetables', 'pumpkins': 'Vegetables',
    'butternut squash': 'Vegetables',
    'acorn squash': 'Vegetables',
    'spaghetti squash': 'Vegetables'
}

# Cuisine mapping
CUISINE = {
    'food': 'Cuisine', 'foods': 'Cuisine', 'cuisine': 'Cuisine', 'dishes': 'Cuisine',
    'recipes': 'Cuisine', 'cooking': 'Cuisine', 'baking': 'Cuisine',
    'indian food': 'Cuisine', 'italian food': 'Cuisine', 'chinese food': 'Cuisine',
    'street food': 'Cuisine', 'desserts': 'Cuisine', 'meals': 'Cuisine',
    'gourmet': 'Cuisine', 'vegetarian': 'Cuisine', 'non vegetarian': 'Cuisine',
    'vegan': 'Cuisine', 'snacks': 'Cuisine', 'delicacies': 'Cuisine'
}

# Culture mapping
CULTURE = {
    'culture': 'Culture', 'tradition': 'Culture', 'customs': 'Culture',
    'heritage': 'Culture', 'festivals': 'Culture', 'art': 'Culture',
    'music': 'Culture', 'dance': 'Culture', 'rituals': 'Culture',
    'languages': 'Culture', 'ethnicity': 'Culture', 'folklore': 'Culture',
    'clothing': 'Culture', 'fashion': 'Culture', 'architecture': 'Culture',
    'religion': 'Culture', 'beliefs': 'Culture', 'values': 'Culture'
}

# Wildlife mapping
WILDLIFE = {
    'wildlife': 'Wildlife', 'animals': 'Wildlife', 'fauna': 'Wildlife',
    'flora and fauna': 'Wildlife', 'jungles': 'Wildlife', 'forests': 'Wildlife',
    'safari': 'Wildlife', 'zoology': 'Wildlife', 'nature': 'Wildlife',
    'national parks': 'Wildlife', 'reserves': 'Wildlife', 'birds': 'Wildlife',
    'marine life': 'Wildlife', 'insects': 'Wildlife', 'endangered species': 'Wildlife'
}

# Planets and Stars mapping
PLANETS_STARS = {
    'mercury': 'Planets and Stars',
    'venus': 'Planets and Stars',
    'earth': 'Planets and Stars',
    'mars': 'Planets and Stars',
    'jupiter': 'Planets and Stars',
    'saturn': 'Planets and Stars',
    'uranus': 'Planets and Stars',
    'neptune': 'Planets and Stars',
    'pluto': 'Planets and Stars',
    'sun': 'Planets and Stars',
    'moon': 'Planets and Stars',
    'solar system': 'Planets and Stars',
    'milky way': 'Planets and Stars',
    'galaxy': 'Planets and Stars',
    'galaxies': 'Planets and Stars',
    'star': 'Planets and Stars',
    'stars': 'Planets and Stars',
    'planet': 'Planets and Stars',
    'planets': 'Planets and Stars',
    'constellation': 'Planets and Stars',
    'constellations': 'Planets and Stars',
    'asteroid': 'Planets and Stars',
    'asteroids': 'Planets and Stars',
    'comet': 'Planets and Stars',
    'comets': 'Planets and Stars',
    'meteor': 'Planets and Stars',
    'meteors': 'Planets and Stars',
    'meteorite': 'Planets and Stars',
    'meteorites': 'Planets and Stars',
    'nebula': 'Planets and Stars',
    'nebulae': 'Planets and Stars',
    'black hole': 'Planets and Stars',
    'black holes': 'Planets and Stars',
    'supernova': 'Planets and Stars',
    'supernovae': 'Planets and Stars',
    'quasar': 'Planets and Stars',
    'quasars': 'Planets and Stars',
    'pulsar': 'Planets and Stars',
    'pulsars': 'Planets and Stars'
}

# Technology terms mapping
TECH_TERMS = {
    'api': 'API',
    'rest': 'API',
    'restful': 'API',
    'graphql': 'API',
    'soap': 'API',
    'endpoint': 'API',
    'endpoints': 'API',
    'microservice': 'API',
    'microservices': 'API',
    'webhook': 'API',
    'webhooks': 'API',
    
    'css': 'CSS',
    'css3': 'CSS',
    'sass': 'CSS',
    'scss': 'CSS',
    'less': 'CSS',
    'stylus': 'CSS',
    'flexbox': 'CSS',
    'grid': 'CSS',
    'bootstrap': 'CSS',
    'tailwind': 'CSS',
    'bulma': 'CSS',
    'material-ui': 'CSS',
    'styled-components': 'CSS',
    
    'javascript': 'JavaScript',
    'js': 'JavaScript',
    'ecmascript': 'JavaScript',
    'es6': 'JavaScript',
    'es2015': 'JavaScript',
    'es2016': 'JavaScript',
    'es2017': 'JavaScript',
    'es2018': 'JavaScript',
    'es2019': 'JavaScript',
    'es2020': 'JavaScript',
    'nodejs': 'JavaScript',
    'node.js': 'JavaScript',
    'npm': 'JavaScript',
    'yarn': 'JavaScript',
    'webpack': 'JavaScript',
    'babel': 'JavaScript',
    'eslint': 'JavaScript',
    'prettier': 'JavaScript',
    'jquery': 'JavaScript',
    'lodash': 'JavaScript',
    'moment': 'JavaScript',
    'axios': 'JavaScript',
    'fetch': 'JavaScript',
    'ajax': 'JavaScript',
    
    'react': 'React',
    'reactjs': 'React',
    'jsx': 'React',
    'hooks': 'React',
    'redux': 'React',
    'mobx': 'React',
    'nextjs': 'React',
    'gatsby': 'React',
    'create-react-app': 'React',
    'react-router': 'React',
    'react-native': 'React',
    
    'blockchain': 'Blockchain',
    'bitcoin': 'Blockchain',
    'ethereum': 'Blockchain',
    'cryptocurrency': 'Cryptocurrency',
    'crypto': 'Cryptocurrency',
    'nft': 'Blockchain',
    'defi': 'Blockchain',
    'smart contract': 'Blockchain',
    'web3': 'Blockchain',
    'dapp': 'Blockchain',
    'mining': 'Cryptocurrency',
    'wallet': 'Cryptocurrency',
    'exchange': 'Cryptocurrency',
    'altcoin': 'Cryptocurrency',
    'stablecoin': 'Cryptocurrency',
    'token': 'Cryptocurrency',
    'ico': 'Cryptocurrency',
    'dao': 'Blockchain',
    
    'ai': 'Artificial Intelligence',
    'artificial intelligence': 'Artificial Intelligence',
    'machine learning': 'Artificial Intelligence',
    'ml': 'Artificial Intelligence',
    'deep learning': 'Artificial Intelligence',
    'neural network': 'Artificial Intelligence',
    'tensorflow': 'Artificial Intelligence',
    'pytorch': 'Artificial Intelligence',
    'scikit-learn': 'Artificial Intelligence',
    'pandas': 'Artificial Intelligence',
    'numpy': 'Artificial Intelligence',
    'keras': 'Artificial Intelligence',
    'nlp': 'Artificial Intelligence',
    'computer vision': 'Artificial Intelligence',
    'chatbot': 'Artificial Intelligence',
    'recommendation system': 'Artificial Intelligence',
    'supervised learning': 'Artificial Intelligence',
    'unsupervised learning': 'Artificial Intelligence',
    'reinforcement learning': 'Artificial Intelligence',
    'cnn': 'Artificial Intelligence',
    'rnn': 'Artificial Intelligence',
    'lstm': 'Artificial Intelligence',
    'gru': 'Artificial Intelligence',
    'transformer': 'Artificial Intelligence',
    'bert': 'Artificial Intelligence',
    'gpt': 'Artificial Intelligence',
    'openai': 'Artificial Intelligence',
    
    'devops': 'DevOps',
    'ci/cd': 'DevOps',
    'continuous integration': 'DevOps',
    'continuous deployment': 'DevOps',
    'docker': 'DevOps',
    'kubernetes': 'DevOps',
    'jenkins': 'DevOps',
    'gitlab': 'DevOps',
    'github actions': 'DevOps',
    'terraform': 'DevOps',
    'ansible': 'DevOps',
    'puppet': 'DevOps',
    'chef': 'DevOps',
    'monitoring': 'DevOps',
    'logging': 'DevOps',
    'prometheus': 'DevOps',
    'grafana': 'DevOps',
    'elk': 'DevOps',
    'nginx': 'DevOps',
    'apache': 'DevOps',
    'load balancer': 'DevOps',
    'microservices': 'DevOps',
    'serverless': 'DevOps',
    'lambda': 'DevOps',
    
    'aws': 'Cloud Computing',
    'amazon web services': 'Cloud Computing',
    'azure': 'Cloud Computing',
    'google cloud': 'Cloud Computing',
    'gcp': 'Cloud Computing',
    'cloud': 'Cloud Computing',
    'ec2': 'Cloud Computing',
    's3': 'Cloud Computing',
    'rds': 'Cloud Computing',
    'lambda': 'Cloud Computing',
    'cloudformation': 'Cloud Computing',
    'vpc': 'Cloud Computing',
    'iam': 'Cloud Computing',
    'cloudwatch': 'Cloud Computing',
    'elastic beanstalk': 'Cloud Computing',
    'ecs': 'Cloud Computing',
    'eks': 'Cloud Computing',
    'fargate': 'Cloud Computing',
    'sqs': 'Cloud Computing',
    'sns': 'Cloud Computing',
    'dynamodb': 'Cloud Computing',
    'redshift': 'Cloud Computing',
    'kinesis': 'Cloud Computing',
    'api gateway': 'Cloud Computing',
    'cloudfront': 'Cloud Computing',
    'route53': 'Cloud Computing',
    'amplify': 'Cloud Computing',
    'cognito': 'Cloud Computing',
    'ses': 'Cloud Computing',
    'workspaces': 'Cloud Computing',
    'connect': 'Cloud Computing',
    'chime': 'Cloud Computing',
    'honeycode': 'Cloud Computing',
    'appflow': 'Cloud Computing',
    'eventbridge': 'Cloud Computing',
    'step functions': 'Cloud Computing',
    'batch': 'Cloud Computing',
    'glue': 'Cloud Computing',
    'emr': 'Cloud Computing',
    'sagemaker': 'Cloud Computing',
    'rekognition': 'Cloud Computing',
    'polly': 'Cloud Computing',
    'lex': 'Cloud Computing',
    'comprehend': 'Cloud Computing',
    'translate': 'Cloud Computing',
    'transcribe': 'Cloud Computing',
    'textract': 'Cloud Computing',
    'forecast': 'Cloud Computing',
    'personalize': 'Cloud Computing',
    'fraud detector': 'Cloud Computing',
    'kendra': 'Cloud Computing',
    'augmented ai': 'Cloud Computing',
    'codewhisperer': 'Cloud Computing',
    'codeguru': 'Cloud Computing',
    'x-ray': 'Cloud Computing',
    'inspector': 'Cloud Computing',
    'macie': 'Cloud Computing',
    'guardduty': 'Cloud Computing',
    'securityhub': 'Cloud Computing',
    'waf': 'Cloud Computing',
    'shield': 'Cloud Computing',
    'certificate manager': 'Cloud Computing',
    'secrets manager': 'Cloud Computing',
    'parameter store': 'Cloud Computing',
    'systems manager': 'Cloud Computing',
    'config': 'Cloud Computing',
    'cloudtrail': 'Cloud Computing',
    'trusted advisor': 'Cloud Computing',
    'well-architected': 'Cloud Computing',
    'organizations': 'Cloud Computing',
    'control tower': 'Cloud Computing',
    'service catalog': 'Cloud Computing',
    'license manager': 'Cloud Computing',
    'resource groups': 'Cloud Computing',
    'tagging': 'Cloud Computing',
    'cost explorer': 'Cloud Computing',
    'budgets': 'Cloud Computing',
    'marketplace': 'Cloud Computing',
    'support': 'Cloud Computing',
    'professional services': 'Cloud Computing',
    'training': 'Cloud Computing',
    'certification': 'Cloud Computing',
    'partner network': 'Cloud Computing',
    'solutions': 'Cloud Computing',
    'architecture': 'Cloud Computing',
    'best practices': 'Cloud Computing',
    'migration': 'Cloud Computing',
    'modernization': 'Cloud Computing',
    'optimization': 'Cloud Computing',
    'cost management': 'Cloud Computing',
    'governance': 'Cloud Computing',
    'compliance': 'Cloud Computing',
    'disaster recovery': 'Cloud Computing',
    'backup': 'Cloud Computing',
    'high availability': 'Cloud Computing',
    'scalability': 'Cloud Computing',
    'performance': 'Cloud Computing',
    'reliability': 'Cloud Computing',
    'security': 'Cloud Computing',
    'privacy': 'Cloud Computing',
    'data protection': 'Cloud Computing',
    'encryption': 'Cloud Computing',
    'access control': 'Cloud Computing',
    'identity management': 'Cloud Computing',
    'single sign-on': 'Cloud Computing',
    'multi-factor authentication': 'Cloud Computing',
    'zero trust': 'Cloud Computing',
    'network security': 'Cloud Computing',
    'application security': 'Cloud Computing',
    'infrastructure security': 'Cloud Computing',
    'cloud security': 'Cloud Computing',
    'cyber security': 'Security',
    'cybersecurity': 'Security',
    'information security': 'Security',
    'data security': 'Security',
    'network security': 'Security',
    'application security': 'Security',
    'web security': 'Security',
    'mobile security': 'Security',
    'endpoint security': 'Security',
    'cloud security': 'Security',
    'infrastructure security': 'Security',
    'security operations': 'Security',
    'incident response': 'Security',
    'threat hunting': 'Security',
    'vulnerability assessment': 'Security',
    'penetration testing': 'Security',
    'security architecture': 'Security',
    'security engineering': 'Security',
    'security governance': 'Security',
    'risk management': 'Security',
    'compliance': 'Security',
    'audit': 'Security',
    'forensics': 'Security',
    'malware': 'Security',
    'virus': 'Security',
    'trojan': 'Security',
    'ransomware': 'Security',
    'phishing': 'Security',
    'social engineering': 'Security',
    'dos': 'Security',
    'ddos': 'Security',
    'sql injection': 'Security',
    'xss': 'Security',
    'csrf': 'Security',
    'owasp': 'Security',
    'firewall': 'Security',
    'ids': 'Security',
    'ips': 'Security',
    'siem': 'Security',
    'soar': 'Security',
    'edr': 'Security',
    'xdr': 'Security',
    'mdr': 'Security',
    'threat intelligence': 'Security',
    'threat modeling': 'Security',
    'risk assessment': 'Security',
    'security awareness': 'Security',
    'security training': 'Security',
    'security culture': 'Security',
    'security metrics': 'Security',
    'security monitoring': 'Security',
    'security automation': 'Security',
    'security orchestration': 'Security',
    'security testing': 'Security',
    'security review': 'Security',
    'security audit': 'Security',
    'security assessment': 'Security',
    'security certification': 'Security',
    'security standard': 'Security',
    'security framework': 'Security',
    'security policy': 'Security',
    'security procedure': 'Security',
    'security control': 'Security',
    'security requirement': 'Security',
    'security specification': 'Security',
    'security design': 'Security',
    'security implementation': 'Security',
    'security deployment': 'Security',
    'security maintenance': 'Security',
    'security support': 'Security',
    'security service': 'Security',
    'security solution': 'Security',
    'security product': 'Security',
    'security tool': 'Security',
    'security platform': 'Security',
    'security technology': 'Security',
    'security innovation': 'Security',
    'security research': 'Security',
    'security development': 'Security',
    'security management': 'Security',
    'security leadership': 'Security',
    'security strategy': 'Security',
    'security vision': 'Security',
    'security mission': 'Security',
    'security objective': 'Security',
    'security goal': 'Security',
    'security outcome': 'Security',
    'security benefit': 'Security',
    'security value': 'Security',
    'security impact': 'Security',
    'security return': 'Security',
    'security investment': 'Security',
    'security budget': 'Security',
    'security cost': 'Security',
    'security expense': 'Security',
    'security resource': 'Security',
    'security capacity': 'Security',
    'security capability': 'Security',
    'security maturity': 'Security',
    'security readiness': 'Security',
    'security posture': 'Security',
    'security stance': 'Security',
    'security position': 'Security',
    'security status': 'Security',
    'security state': 'Security',
    'security condition': 'Security',
    'security situation': 'Security',
    'security environment': 'Security',
    'security context': 'Security',
    'security landscape': 'Security',
    'security ecosystem': 'Security',
    'security community': 'Security',
    'security industry': 'Security',
    'security market': 'Security',
    'security sector': 'Security',
    'security domain': 'Security',
    'security field': 'Security',
    'security area': 'Security',
    'security space': 'Security',
    'security realm': 'Security',
    'security sphere': 'Security',
    'security world': 'Security',
    'security universe': 'Security',
    'security dimension': 'Security',
    'security aspect': 'Security',
    'security facet': 'Security',
    'security element': 'Security',
    'security component': 'Security',
    'security part': 'Security',
    'security piece': 'Security',
    'encryption': 'Security',
    
    'mysql': 'Database',
    'postgresql': 'Database',
    'mongodb': 'Database',
    'redis': 'Database',
    'cassandra': 'Database',
    'elasticsearch': 'Database',
    'neo4j': 'Database',
    'dynamodb': 'Database',
    'sqlite': 'Database',
    'oracle': 'Database',
    'sql server': 'Database',
    'mariadb': 'Database',
    'couchdb': 'Database',
    'influxdb': 'Database',
    'memcached': 'Database',
    'riak': 'Database',
    'hbase': 'Database',
    'couchbase': 'Database',
    'firestore': 'Database',
    'realm': 'Database',
    'database': 'Database',
    'db': 'Database',
    'sql': 'Database',
    'nosql': 'Database',
    'acid': 'Database',
    'transaction': 'Database',
    'index': 'Database',
    'query': 'Database',
    'schema': 'Database',
    'migration': 'Database',
    'backup': 'Database',
    'restore': 'Database',
    'replication': 'Database',
    'sharding': 'Database',
    'clustering': 'Database',
    'normalization': 'Database',
    'denormalization': 'Database',
    'connection pooling': 'Database',
    'orm': 'Database',
    'data modeling': 'Database',
    'entity relationship': 'Database',
    'foreign key': 'Database',
    'primary key': 'Database',
    'unique key': 'Database',
    'constraint': 'Database',
    'trigger': 'Database',
    'stored procedure': 'Database',
    'function': 'Database',
    'view': 'Database',
    'materialized view': 'Database',
    'cursor': 'Database',
    'prepared statement': 'Database',
    'batch processing': 'Database',
    'bulk insert': 'Database',
    'data warehouse': 'Database',
    'data lake': 'Database',
    'etl': 'Database',
    'elt': 'Database',
    'oltp': 'Database',
    'olap': 'Database',
    'consistency': 'Database',
    'availability': 'Database',
    'partition tolerance': 'Database',
    'cap theorem': 'Database',
    'eventual consistency': 'Database',
    'strong consistency': 'Database',
    'weak consistency': 'Database',
    'distributed database': 'Database',
    'master-slave': 'Database',
    'master-master': 'Database',
    'peer-to-peer': 'Database',
    'read replica': 'Database',
    'replica set': 'Database',
    'cluster': 'Database',
    'shard': 'Database',
    'node': 'Database',
    'checkpoint': 'Database',
    'redo log': 'Database',
    'undo log': 'Database',
    'wal': 'Database',
    'rollback': 'Database',
    'commit': 'Database',
    'savepoint': 'Database',
    'autocommit': 'Database',
    'serializable': 'Database',
    'repeatable read': 'Database',
    'read committed': 'Database',
    'read uncommitted': 'Database',
    'dirty read': 'Database',
    'phantom read': 'Database',
    'non-repeatable read': 'Database',
    'mvcc': 'Database',
    'indexing': 'Database',
    'query planner': 'Database',
    'execution plan': 'Database',
    'query optimization': 'Database',
    'latency': 'Database',
    'throughput': 'Database',
    'iops': 'Database',
    'in-memory database': 'Database',
    'disk-based database': 'Database',
    'columnar store': 'Database',
    'document store': 'Database',
    'key-value store': 'Database',
    'graph database': 'Database',
    'time-series database': 'Database',
    
    'framework': 'Framework',
    'library': 'Framework',
    'angular': 'Framework',
    'vue': 'Framework',
    'svelte': 'Framework',
    'ember': 'Framework',
    'backbone': 'Framework',
    'knockout': 'Framework',
    'django': 'Framework',
    'flask': 'Framework',
    'fastapi': 'Framework',
    'spring': 'Framework',
    'laravel': 'Framework',
    'symfony': 'Framework',
    'codeigniter': 'Framework',
    'cakephp': 'Framework',
    'zend': 'Framework',
    'yii': 'Framework',
    'phalcon': 'Framework',
    'slim': 'Framework',
    'lumen': 'Framework',
    'express': 'Framework',
    'koa': 'Framework',
    'hapi': 'Framework',
    'nestjs': 'Framework',
    'meteor': 'Framework',
    'sails': 'Framework',
    'adonis': 'Framework',
    'strapi': 'Framework',
    'gatsby': 'Framework',
    'nuxt': 'Framework',
    'next': 'Framework',
    'remix': 'Framework',
    'sveltekit': 'Framework',
    'astro': 'Framework',
    'solid': 'Framework',
    'alpine': 'Framework',
    'stimulus': 'Framework',
    'turbo': 'Framework',
    'hotwire': 'Framework',
    'phoenix': 'Framework',
    'rails': 'Framework',
    'sinatra': 'Framework',
    'hanami': 'Framework',
    'grape': 'Framework',
    'padrino': 'Framework',
    'cuba': 'Framework',
    'roda': 'Framework',
    'rspec': 'Framework',
    'minitest': 'Framework',
    'cucumber': 'Framework',
    'factory_bot': 'Framework',
    'faker': 'Framework',
    'vcr': 'Framework',
    'webmock': 'Framework',
    'capybara': 'Framework',
    'selenium': 'Framework',
    'watir': 'Framework',
    'poltergeist': 'Framework',
    'devise': 'Framework',
    'omniauth': 'Framework',
    'cancancan': 'Framework',
    'pundit': 'Framework',
    'rolify': 'Framework',
    'doorkeeper': 'Framework',
    'jwt': 'Framework',
    'bcrypt': 'Framework',
    'scrypt': 'Framework',
    'argon2': 'Framework',
    'elasticsearch-rails': 'Framework',
    'searchkick': 'Framework',
    'ransack': 'Framework',
    'kaminari': 'Framework',
    'will_paginate': 'Framework',
    'activerecord': 'Framework',
    'datamapper': 'Framework',
    'mongoid': 'Framework',

    'architecture': 'Software Architecture',
    'software architecture': 'Software Architecture',
    'microservices': 'Software Architecture',
    'monolith': 'Software Architecture',
    'event-driven': 'Software Architecture',
    'layered architecture': 'Software Architecture',
    'hexagonal architecture': 'Software Architecture',
    'onion architecture': 'Software Architecture',
    'clean architecture': 'Software Architecture',
    'modular architecture': 'Software Architecture',
    'client-server': 'Software Architecture',
    'mvc': 'Software Architecture',
    'mvvm': 'Software Architecture',
    'mvp': 'Software Architecture',
    'soa': 'Software Architecture',
    'serverless': 'Software Architecture',
    'cloud-native': 'Software Architecture',
    'domain-driven design': 'Software Architecture',
    'ddd': 'Software Architecture',
    'event sourcing': 'Software Architecture',
    'cqrs': 'Software Architecture',
    'message broker': 'Software Architecture',
    'message queue': 'Software Architecture',
    'pubsub': 'Software Architecture',
    'load balancer': 'Software Architecture',
    'reverse proxy': 'Software Architecture',
    'api gateway': 'Software Architecture',
    'service mesh': 'Software Architecture',
    'scalability': 'Software Architecture',
    'availability': 'Software Architecture',
    'reliability': 'Software Architecture',
    'resilience': 'Software Architecture',
    'fault tolerance': 'Software Architecture',
    'observability': 'Software Architecture',
    'design pattern': 'Software Architecture',
    'singleton': 'Software Architecture',
    'factory': 'Software Architecture',
    'strategy pattern': 'Software Architecture',
    'adapter pattern': 'Software Architecture',
    'repository pattern': 'Software Architecture',
    'bridge pattern': 'Software Architecture',

    'backend': 'Backend',
    'server': 'Backend',
    'server-side': 'Backend',
    'api': 'Backend',
    'rest api': 'Backend',
    'graphql': 'Backend',
    'rpc': 'Backend',
    'authentication': 'Backend',
    'authorization': 'Backend',
    'jwt': 'Backend',
    'oauth': 'Backend',
    'session': 'Backend',
    'cookie': 'Backend',
    'middleware': 'Backend',
    'webhook': 'Backend',
    'cron': 'Backend',
    'job queue': 'Backend',
    'background task': 'Backend',
    'message queue': 'Backend',
    'socket': 'Backend',
    'websocket': 'Backend',
    'load balancer': 'Backend',
    'rate limiting': 'Backend',
    'throttling': 'Backend',
    'caching': 'Backend',
    'redis': 'Backend',
    'database': 'Backend',
    'orm': 'Backend',
    'sql': 'Backend',
    'nosql': 'Backend',
    'restful': 'Backend',
    'http': 'Backend',
    'https': 'Backend',
    'ssl': 'Backend',
    'tls': 'Backend',
    'reverse proxy': 'Backend',
    'nginx': 'Backend',
    'apache': 'Backend',
    'flask': 'Backend',
    'express': 'Backend',
    'spring boot': 'Backend',
    'fastapi': 'Backend',
    'django': 'Backend'
}

# Career mapping
CAREER = {
    'career': 'Career',
    'job': 'Career',
    'profession': 'Career',
    'occupation': 'Career',
    'role': 'Career',
    'position': 'Career',
    'interview': 'Career',
    'resume': 'Career',
    'cv': 'Career',
    'cover letter': 'Career',
    'portfolio': 'Career',
    'offer letter': 'Career',
    'salary': 'Career',
    'promotion': 'Career',
    'hiring': 'Career',
    'recruitment': 'Career',
    'placement': 'Career',
    'job search': 'Career',
    'internship': 'Career',
    'freelance': 'Career',
    'contract': 'Career',
    'full-time': 'Career',
    'part-time': 'Career',
    'remote': 'Career',
    'onsite': 'Career',
    'hybrid': 'Career',
    'resignation': 'Career',
    'job switch': 'Career',
    'networking': 'Career',
    'mentorship': 'Career',
    'career advice': 'Career',
    'skill development': 'Career',
    'growth': 'Career',
    'soft skills': 'Career',
    'communication': 'Career',
    'negotiation': 'Career',
    'linkedin': 'Career',
    'headhunter': 'Career',
    'hr': 'Career',
    'human resources': 'Career',
    'team lead': 'Career',
    'manager': 'Career',

    'software engineer': 'Career',
    'software developer': 'Career',
    'frontend developer': 'Career',
    'backend developer': 'Career',
    'fullstack developer': 'Career',
    'web developer': 'Career',
    'mobile developer': 'Career',
    'android developer': 'Career',
    'ios developer': 'Career',
    'data scientist': 'Career',
    'machine learning engineer': 'Career',
    'ai engineer': 'Career',
    'data analyst': 'Career',
    'devops engineer': 'Career',
    'cloud engineer': 'Career',
    'site reliability engineer': 'Career',
    'qa engineer': 'Career',
    'test engineer': 'Career',
    'automation engineer': 'Career',
    'database administrator': 'Career',
    'network engineer': 'Career',
    'cybersecurity analyst': 'Career',
    'ethical hacker': 'Career',
    'product manager': 'Career',
    'project manager': 'Career',
    'scrum master': 'Career',
    'ui designer': 'Career',
    'ux designer': 'Career',
    'graphic designer': 'Career',
    'technical writer': 'Career',
    'system administrator': 'Career',
    'business analyst': 'Career',
    'solutions architect': 'Career',
    'tech lead': 'Career',
    'cto': 'Career',
    'cio': 'Career',

    'civil engineer': 'Career',
    'mechanical engineer': 'Career',
    'electrical engineer': 'Career',
    'electronics engineer': 'Career',
    'aerospace engineer': 'Career',
    'chemical engineer': 'Career',
    'architect': 'Career',
    'interior designer': 'Career',
    'accountant': 'Career',
    'chartered accountant': 'Career',
    'financial analyst': 'Career',
    'banker': 'Career',
    'lawyer': 'Career',
    'doctor': 'Career',
    'nurse': 'Career',
    'dentist': 'Career',
    'pharmacist': 'Career',
    'teacher': 'Career',
    'professor': 'Career',
    'researcher': 'Career',
    'scientist': 'Career',
    'pilot': 'Career',
    'chef': 'Career',
    'writer': 'Career',
    'journalist': 'Career',
    'photographer': 'Career',
    'videographer': 'Career',
    'editor': 'Career',
    'marketing manager': 'Career',
    'sales executive': 'Career',
    'hr manager': 'Career',
    'entrepreneur': 'Career',
    'startup founder': 'Career',
    'consultant': 'Career'
}

# Movies and Entertainment mapping
MOVIES_AND_ENTERTAINMENT = {
    'movies': 'Movies and Entertainment',
    'movie': 'Movies and Entertainment',
    'cinema': 'Movies and Entertainment',
    'hollywood': 'Movies and Entertainment',
    'bollywood': 'Movies and Entertainment',
    'tollywood': 'Movies and Entertainment',
    'anime': 'Movies and Entertainment',
    'manga': 'Movies and Entertainment',
    'series': 'Movies and Entertainment',
    'tv show': 'Movies and Entertainment',
    'web series': 'Movies and Entertainment',
    'netflix': 'Movies and Entertainment',
    'prime video': 'Movies and Entertainment',
    'hotstar': 'Movies and Entertainment',
    'disney+': 'Movies and Entertainment',
    'hbo': 'Movies and Entertainment',
    'action': 'Movies and Entertainment',
    'comedy': 'Movies and Entertainment',
    'thriller': 'Movies and Entertainment',
    'drama': 'Movies and Entertainment',
    'romance': 'Movies and Entertainment',
    'horror': 'Movies and Entertainment',
    'documentary': 'Movies and Entertainment',
    'biopic': 'Movies and Entertainment',
    'film': 'Movies and Entertainment',
    'cinematography': 'Movies and Entertainment',
    'actor': 'Movies and Entertainment',
    'actress': 'Movies and Entertainment',
    'director': 'Movies and Entertainment',
    'screenplay': 'Movies and Entertainment',
    'soundtrack': 'Movies and Entertainment',
    'music': 'Movies and Entertainment',
    'binge': 'Movies and Entertainment'
}
